In [5]:
import os
!pip install -r requirements.txt

[notice] A new release of pip is available: 24.3.1 -> 25.3
[notice] To update, run: pip install --upgrade pip
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

In [1]:
import ace_lib as ace
import helpful_functions as hf
import pandas as pd
import plotly.express as px
from tqdm import tqdm

In [2]:
s = ace.start_session()
ace.check_session_timeout(s)

14399.548148

In [10]:
s = ace.check_session_and_relogin(s)

In [31]:
# datasets_df = ace.get_datasets(
#     s,
#     region='IND',
#     universe='TOP500',
#     delay=1,
#     theme='false'
# )
datasets_df = ace.get_datasets(
    s,
    region='USD',
    universe='TOPSP500',
    delay=1,
    theme='false'
)
# datasets_df = ace.get_datasets(
#     s,
#     region='CHN',
#     universe='TOP2000U',
#     delay=1,
# )
# datasets_df = ace.get_datasets(
#     s,
#     region='EUR',
#     universe='TOPCS1600',
#     delay=1,
# )
# print(len(datasets_df))
# datasets_df.head()

ValueError: No objects to concatenate

In [44]:
"""
1	8  Dec - 14 Dec	| Fundamental, Earnings, Short Interest, PV, Broker
2	15 Dec - 21 Dec	| Insiders, Sentiment, News, Other, Option
3	22 Dec - 28 Dec	| Institutions, Analyst, Risk
4	29 Dec - 4  Jan	| Macro, Model
"""

dataset_ids = []
for cat in datasets_df['category_id'].unique():
    cat_df = datasets_df[datasets_df['category_id']==cat]
    print(cat, len(cat_df))
    dataset_ids += cat_df['id'].tolist()
    print(cat_df['id'].tolist())
    print()
print(len(dataset_ids))

analyst 5
['analyst10', 'analyst11', 'analyst14', 'analyst45', 'analyst69']

fundamental 5
['fundamental23', 'fundamental27', 'fundamental4', 'fundamental5', 'fundamental6']

macro 2
['macro61', 'other551']

model 15
['model135', 'model138', 'model14', 'model144', 'model170', 'model175', 'model207', 'model243', 'model26', 'model291', 'model307', 'model31', 'model36', 'model37', 'model39']

news 9
['news11', 'news21', 'news29', 'news38', 'news46', 'news50', 'news7', 'news76', 'news79']

other 8
['other315', 'other370', 'other496', 'other545', 'other546', 'other561', 'other592', 'other715']

pv 7
['pv1', 'pv106', 'pv173', 'pv25', 'pv27', 'pv29', 'pv30']

risk 1
['risk72']

sentiment 1
['sentiment27']

shortinterest 1
['shortinterest5']

socialmedia 1
['socialmedia12']

55

In [65]:
import time
res_df = ace.get_datafields(
    s,
    region='IND',
    universe='TOP500',
    delay=1,
)
# res_df = ace.get_datafields(
#     s,
#     region='USA',
#     universe='TOPSP500',
#     delay=1,
# )
# res_df = ace.get_datafields(
#     s,
#     region='ASI',
#     universe='MINVOL1M',
#     delay=1,
# )
# res_df = ace.get_datafields(
#     s,
#     region='EUR',
#     universe='TOPCS1600',
#     delay=1,
# )
# res_df = ace.get_datafields(
#     s,
#     region='CHN',
#     universe='TOP2000U',
#     delay=1,
# )
print(res_df.columns)
print(res_df.shape)
res_df.head()

2026-03-29 17:59:32,949 - ace - INFO - Getting fields for: region=IND, delay=1, universe=TOP500

Index(['id', 'description', 'dataset', 'category', 'subcategory', 'region',
       'delay', 'universe', 'type', 'dateCoverage', 'coverage', 'userCount',
       'alphaCount', 'pyramidMultiplier', 'themes', 'dataset_id',
       'dataset_name', 'category_id', 'category_name', 'subcategory_id',
       'subcategory_name'],
      dtype='object')
(7197, 21)

,id,description,dataset,category,subcategory,region,delay,universe,type,dateCoverage,...,userCount,alphaCount,pyramidMultiplier,themes,dataset_id,dataset_name,category_id,category_name,subcategory_id,subcategory_name
0,absolute_price_change_today_2,Change in security price since the previous da...,"{'id': 'analyst45', 'name': 'Analyst Trade Ide...","{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",IND,1,TOP500,VECTOR,1.0,...,62,79,1.5,[],analyst45,Analyst Trade Ideas,analyst,Analyst,analyst-analyst-estimates,Analyst Estimates
1,accounts_receivable_current_assets,Accounts receivable included in current assets...,"{'id': 'fundamental23', 'name': 'Fundamental P...","{'id': 'fundamental', 'name': 'Fundamental'}","{'id': 'fundamental-fundamental-data', 'name':...",IND,1,TOP500,MATRIX,1.0,...,119,148,1.5,[],fundamental23,Fundamental Point in Time Data,fundamental,Fundamental,fundamental-fundamental-data,Fundamental Data
2,accrual_factor_score_change_1d,Change in accruals factor percentile score ove...,"{'id': 'model31', 'name': 'Earnings Quality Mo...","{'id': 'model', 'name': 'Model'}","{'id': 'model-valuation-models', 'name': 'Valu...",IND,1,TOP500,MATRIX,1.0,...,33,51,1.3,[],model31,Earnings Quality Model,model,Model,model-valuation-models,Valuation Models
3,accrual_factor_score_change_1fy,Change in accruals factor percentile score ove...,"{'id': 'model31', 'name': 'Earnings Quality Mo...","{'id': 'model', 'name': 'Model'}","{'id': 'model-valuation-models', 'name': 'Valu...",IND,1,TOP500,MATRIX,1.0,...,30,41,1.3,[],model31,Earnings Quality Model,model,Model,model-valuation-models,Valuation Models
4,accrual_factor_score_current,Percentile score for accruals factors for the ...,"{'id': 'model31', 'name': 'Earnings Quality Mo...","{'id': 'model', 'name': 'Model'}","{'id': 'model-valuation-models', 'name': 'Valu...",IND,1,TOP500,MATRIX,1.0,...,71,100,1.3,[],model31,Earnings Quality Model,model,Model,model-valuation-models,Valuation Models

In [66]:
print(res_df['type'].value_counts())

type
MATRIX      4059
VECTOR      2877
GROUP        244
SYMBOL        16
UNIVERSE       1
Name: count, dtype: int64

In [58]:
# old_vector_res_df = pd.read_csv('../backfill/EUR/[field_df]EUR_TOPCS1600_vector_delay1.csv',index_col=0).drop_duplicates()
# print(old_vector_res_df.shape)

vector_res_df = res_df[res_df['type']=='VECTOR']
# vector_res_df.to_csv('../backfill/INDTOP500/[field_df]IND_TOP500_vector_delay1.csv')
print(vector_res_df.shape)

(2877, 21)

In [67]:
# old_matrix_res_df = pd.read_csv('../backfill/EUR/[field_df]EUR_TOPCS1600_matrix_delay1.csv',index_col=0).drop_duplicates()
# print(old_matrix_res_df.shape)

matrix_res_df = res_df[res_df['type']=='MATRIX']
# matrix_res_df.to_csv('../backfill/INDTOP500/[field_df]IND_TOP500_matrix_delay1.csv')
print(matrix_res_df.shape)

(4059, 21)

In [3]:
# res_df.to_csv('../backfill/EUR/[field_df]EUR_TOPCS1600_vector_delay1.csv')
# res_df.to_csv('../backfill/EUR/matrix_field_df_EUR_TOP2500_delay0.csv')
# res_df.to_csv('../backfill/GLB/vector_field_df_EUR_TOP2500_delay0.csv')
# res_df.to_csv('../backfill/AMR/[field_df]AMR_TOP600_matrix_delay1.csv')
# res_df.to_csv('../backfill/AMR/[field_df]AMR_TOP600_vector_delay1.csv')
# res_df.to_csv('../backfill/AMR/[field_df]AMR_TOP600_matrix_delay0.csv')

# res_df.to_csv('../backfill/CHNTOP2000U/[field_df]CHN_TOP2000U_vector_delay1.csv')
# res_df = pd.read_csv('../backfill/EUR/[field_df]EUR_TOPCS1600_vector_delay1.csv',index_col=0).drop_duplicates()
# res_df = pd.read_csv('../backfill/EUR/[field_df]EUR_TOPCS1600_matrix_delay1.csv',index_col=0).drop_duplicates()
# res_df = pd.read_csv('../backfill/GLB/[field_df]GLB_TOP3000_matrix_delay1.csv',index_col=0).drop_duplicates()
# res_df = pd.read_csv('../backfill/GLB/[field_df]GLB_TOP3000_vector_delay1.csv',index_col=0).drop_duplicates()
# res_df = pd.read_csv('../backfill/AMR/[field_df]AMR_TOP600_vector_delay1.csv',index_col=0)
# res_df = pd.read_csv('../backfill/AMR/[field_df]AMR_TOP600_matrix_delay1.csv',index_col=0)
# res_df = pd.read_csv('../backfill/ASIMINVOL1M/[field_df]ASI_MINVOL1M_vector_delay1.csv')
# res_df = pd.read_csv('../backfill/ASIMINVOL1M/[field_df]ASI_MINVOL1M_matrix_delay1.csv')

# res_df = pd.read_csv('../backfill/USATOPSP500/[field_df]USA_TOPSP500_vector_delay1.csv')
# res_df = pd.read_csv('../backfill/USATOPSP500/[field_df]USA_TOPSP500_matrix_delay1.csv')
# res_df = pd.read_csv('../backfill/INDTOP500/[field_df]IND_TOP500_matrix_delay1.csv')
res_df = pd.read_csv('../backfill/INDTOP500/[field_df]IND_TOP500_vector_delay1.csv')

print(res_df.shape)
res_df

(2877, 22)

,Unnamed: 0,id,description,dataset,category,subcategory,region,delay,universe,type,...,userCount,alphaCount,pyramidMultiplier,themes,dataset_id,dataset_name,category_id,category_name,subcategory_id,subcategory_name
0,0,absolute_price_change_today_2,Change in security price since the previous da...,"{'id': 'analyst45', 'name': 'Analyst Trade Ide...","{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",IND,1,TOP500,VECTOR,...,62,79,1.5,[],analyst45,Analyst Trade Ideas,analyst,Analyst,analyst-analyst-estimates,Analyst Estimates
1,7,active_notional_value_leg1,Monetary notional amount effective for leg 1 o...,"{'id': 'other315', 'name': 'Equity Swap Data'}","{'id': 'other', 'name': 'Other'}","{'id': 'other-aiml-data', 'name': 'AI/ML Data'}",IND,1,TOP500,VECTOR,...,0,0,1.4,[],other315,Equity Swap Data,other,Other,other-aiml-data,AI/ML Data
2,8,actuals_reporting_currency,Home currency of instrument,"{'id': 'analyst4', 'name': 'Analyst Estimate D...","{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",IND,1,TOP500,VECTOR,...,21,25,1.5,[],analyst4,Analyst Estimate Data for Equity,analyst,Analyst,analyst-analyst-estimates,Analyst Estimates
3,9,actual_capex_value,Actual value reported for capital expenditure.,"{'id': 'analyst44', 'name': 'Integrated Broker...","{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-crowdsourced-estimates', 'name...",IND,1,TOP500,VECTOR,...,44,53,1.5,[],analyst44,Integrated Broker Estimates,analyst,Analyst,analyst-crowdsourced-estimates,Crowdsourced Estimates
4,10,actual_investment_round_total,Actual total amount for the investment round.,"{'id': 'news23', 'name': 'MnA Deals Data'}","{'id': 'news', 'name': 'News'}","{'id': 'news-news', 'name': 'News'}",IND,1,TOP500,VECTOR,...,21,24,1.5,[],news23,MnA Deals Data,news,News,news-news,News
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2872,7178,workplace_culture_sentiment,Sentiment score reflecting reviewer opinions a...,"{'id': 'other567', 'name': 'Employee Review Da...","{'id': 'other', 'name': 'Other'}","{'id': 'other-event-data', 'name': 'Event Data'}",IND,1,TOP500,VECTOR,...,5,5,1.4,[],other567,Employee Review Data,other,Other,other-event-data,Event Data
2873,7187,workplace_inclusion_score,A score reflecting diversity and inclusion pra...,"{'id': 'model176', 'name': 'Non-Financial Metr...","{'id': 'model', 'name': 'Model'}","{'id': 'model-consumer-models', 'name': 'Consu...",IND,1,TOP500,VECTOR,...,1,1,1.3,[],model176,Non-Financial Metric Models,model,Model,model-consumer-models,Consumer Models
2874,7188,workplace_safety_incident_score,Rates the frequency of workplace accidents and...,"{'id': 'model176', 'name': 'Non-Financial Metr...","{'id': 'model', 'name': 'Model'}","{'id': 'model-consumer-models', 'name': 'Consu...",IND,1,TOP500,VECTOR,...,1,1,1.3,[],model176,Non-Financial Metric Models,model,Model,model-consumer-models,Consumer Models
2875,7189,work_life_balance_rating,Rating for work-life balance by the reviewer.,"{'id': 'other567', 'name': 'Employee Review Da...","{'id': 'other', 'name': 'Other'}","{'id': 'other-event-data', 'name': 'Event Data'}",IND,1,TOP500,VECTOR,...,4,6,1.4,[],other567,Employee Review Data,other,Other,other-event-data,Event Data
2876,7190,work_life_balance_sentiment_score,Sentiment score for work-life balance based on...,"{'id': 'other567', 'name': 'Employee Review Da...","{'id': 'other', 'name': 'Other'}","{'id': 'other-event-data', 'name': 'Event Data'}",IND,1,TOP500,VECTOR,...,2,2,1.4,[],other567,Employee Review Data,other,Other,other-event-data,Event Data

In [4]:
for cat in res_df['category_id'].unique():
    cat_df = res_df[res_df['category_id']==cat]
    print(cat, len(cat_df))

analyst 1152
other 381
news 535
fundamental 127
earnings 55
model 486
pv 73
option 40
insiders 10
sentiment 18

In [5]:
cat = 'analyst'
# cat = 'earnings'
# cat = 'fundamental'
# cat = 'insiders'
# cat = 'institutions'
# cat = 'imbalance'
# cat = 'model'
# cat = 'macro'
# cat = 'news'
# cat = 'option'
# cat = 'other'
# cat = 'pv'
# cat = 'risk'
# cat = 'sentiment'
# cat = 'shortinterest'
# cat = 'socialmedia'

cat_df = res_df[res_df['category_id']==cat]
cat_df

,Unnamed: 0,id,description,dataset,category,subcategory,region,delay,universe,type,...,userCount,alphaCount,pyramidMultiplier,themes,dataset_id,dataset_name,category_id,category_name,subcategory_id,subcategory_name
0,0,absolute_price_change_today_2,Change in security price since the previous da...,"{'id': 'analyst45', 'name': 'Analyst Trade Ide...","{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",IND,1,TOP500,VECTOR,...,62,79,1.5,[],analyst45,Analyst Trade Ideas,analyst,Analyst,analyst-analyst-estimates,Analyst Estimates
2,8,actuals_reporting_currency,Home currency of instrument,"{'id': 'analyst4', 'name': 'Analyst Estimate D...","{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",IND,1,TOP500,VECTOR,...,21,25,1.5,[],analyst4,Analyst Estimate Data for Equity,analyst,Analyst,analyst-analyst-estimates,Analyst Estimates
3,9,actual_capex_value,Actual value reported for capital expenditure.,"{'id': 'analyst44', 'name': 'Integrated Broker...","{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-crowdsourced-estimates', 'name...",IND,1,TOP500,VECTOR,...,44,53,1.5,[],analyst44,Integrated Broker Estimates,analyst,Analyst,analyst-crowdsourced-estimates,Crowdsourced Estimates
6,12,actual_tbvps_currency,Currency in which the actual tangible book val...,"{'id': 'analyst44', 'name': 'Integrated Broker...","{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-crowdsourced-estimates', 'name...",IND,1,TOP500,VECTOR,...,15,17,1.5,[],analyst44,Integrated Broker Estimates,analyst,Analyst,analyst-crowdsourced-estimates,Crowdsourced Estimates
7,13,actual_tbvps_value,Actual value reported for tangible book value ...,"{'id': 'analyst44', 'name': 'Integrated Broker...","{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-crowdsourced-estimates', 'name...",IND,1,TOP500,VECTOR,...,5,5,1.5,[],analyst44,Integrated Broker Estimates,analyst,Analyst,analyst-crowdsourced-estimates,Crowdsourced Estimates
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2860,7113,unrealized_return_value,Unrealized return on open positions in the tra...,"{'id': 'analyst45', 'name': 'Analyst Trade Ide...","{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",IND,1,TOP500,VECTOR,...,7,8,1.5,[],analyst45,Analyst Trade Ideas,analyst,Analyst,analyst-analyst-estimates,Analyst Estimates
2861,7114,updated_field_value_3,"New value after a change in stop loss, target ...","{'id': 'analyst45', 'name': 'Analyst Trade Ide...","{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",IND,1,TOP500,VECTOR,...,2,3,1.5,[],analyst45,Analyst Trade Ideas,analyst,Analyst,analyst-analyst-estimates,Analyst Estimates
2862,7115,updated_value_after_change_limited,"New value after a change in stop loss, target ...","{'id': 'analyst45', 'name': 'Analyst Trade Ide...","{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",IND,1,TOP500,VECTOR,...,2,2,1.5,[],analyst45,Analyst Trade Ideas,analyst,Analyst,analyst-analyst-estimates,Analyst Estimates
2864,7122,volume_weighted_entry_price_2,Average share price weighted by purchase volume.,"{'id': 'analyst45', 'name': 'Analyst Trade Ide...","{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",IND,1,TOP500,VECTOR,...,4,4,1.5,[],analyst45,Analyst Trade Ideas,analyst,Analyst,analyst-analyst-estimates,Analyst Estimates
2865,7123,volume_weighted_initial_price,Average share price weighted by volume of each...,"{'id': 'analyst45', 'name': 'Analyst Trade Ide...","{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",IND,1,TOP500,VECTOR,...,6,6,1.5,[],analyst45,Analyst Trade Ideas,analyst,Analyst,analyst-analyst-estimates,Analyst Estimates

In [6]:
# region = 'EUR'
# region = 'CHN'
# region = 'GLB'
# region = 'ASI'
# region = 'USA'
region = 'IND'

# universe = 'TOPCS1600'
# universe = 'TOP2000U'
# universe='TOP3000'
# universe = 'MINVOL1M'
# universe = 'TOPSP500'
universe = 'TOP500'

# neutral = 'COUNTRY'
# neutral = 'MARKET'
# neutral = 'INDUSTRY'
neutral = 'REVERSION_AND_MOMENTUM'
# neutral = 'SLOW'
# neutral = 'FAST'
# neutral = 'SLOW_AND_FAST'
# neutral = 'CROWDING'
# neutral = 'STATISTICAL'

params = {
    # 'region':   'AMR', 'universe': 'TOP600',
    # 'region':   'GLB', 'universe': 'TOP3000',
    'region':   region,
    'universe': universe,
    'delay':    1,
    'neutralization': neutral
}
doc = f'{region}{universe}/{neutral}'

# delay = 'D0'
delay = 'D1'

# type = 'matrix_rank'
# type = 'matrix_rank_delta5'
# type = 'matrix_rank_delta60'
# type = 'matrix_rank_backfill5'

type = 'vector_rank'
# type = 'vector_rank_delta5'
# type = 'vector_rank_delta60'
# type = 'vector_rank_backfill5'

path_dict = {
    'matrix_rank': {
        'input_file_prefix':  f'simulate_data_results_{delay}_rank({cat})_',
        'output_file_path': f'../backfill/{doc}/[backfill_result]{cat}_matrix_{delay}_results.csv'
    },
    'matrix_rank_delta5':{
        'input_file_prefix': f'simulate_data_results_{delay}_rank(delta({cat},5))_',
        'output_file_path': f'../backfill/{doc}/[backfill_result]{cat}_matrix_{delay}_delta5_results.csv'
    },
    'matrix_rank_delta60':{
        'input_file_prefix': f'simulate_data_results_{delay}_rank(delta({cat},60))_',
        'output_file_path': f'../backfill/{doc}/[backfill_result]{cat}_matrix_{delay}_delta60_results.csv'
    },
    'matrix_rank_backfill5':{
        'input_file_prefix': f'simulate_data_results_{delay}_rank(ts_backfill({cat},5))_',
        'output_file_path': f'../backfill/{doc}/[backfill_result]{cat}_matrix_{delay}_backfill5_results.csv'
    },
    'vector_rank': {
        'input_file_prefix': f'simulate_data_results_{delay}_rank(vec_avg({cat}))_',
        'output_file_path': f'../backfill/{doc}/[backfill_result]{cat}_vector_{delay}_results.csv'
    },
    'vector_rank_delta5':{
        'input_file_prefix': f'simulate_data_results_{delay}_rank(delta(vec_avg({cat}),5))_',
        'output_file_path': f'../backfill/{doc}/[backfill_result]{cat}_vector_{delay}_delta5_results.csv'
    },
    'vector_rank_delta60': {
        'input_file_prefix': f'simulate_data_results_{delay}_rank(delta(vec_avg({cat}),60))_',
        'output_file_path': f'../backfill/{doc}/[backfill_result]{cat}_vector_{delay}_delta60_results.csv'
    },
    'vector_rank_backfill5':{
        'input_file_prefix': f'simulate_data_results_{delay}_rank(ts_backfill(vec_avg({cat}),5))_',
        'output_file_path': f'../backfill/{doc}/[backfill_result]{cat}_vector_{delay}_backfill5_results.csv'
    },
}
input_file_prefix = path_dict[type]['input_file_prefix']
output_file_path = path_dict[type]['output_file_path']
print(input_file_prefix)
print(output_file_path)

expression_list_dict = {
    'matrix_rank': [f"rank({x})" for x in cat_df.id.values],
    'matrix_rank_delta5': [f"rank(ts_delta({x},5))" for x in cat_df.id.values],
    'matrix_rank_delta60': [f"rank(ts_delta({x},60))" for x in cat_df.id.values],
    'matrix_rank_backfill5': [f"rank(ts_backfill({x},5))" for x in cat_df.id.values],
    'matrix_rank_backfill60': [f"rank(ts_backfill({x},60))" for x in cat_df.id.values],

    'vector_rank': [f"rank(vec_avg({x}))" for x in cat_df.id.values.tolist()],
    'vector_rank_delta5': [f"rank(ts_delta(vec_avg({x}),5))" for x in cat_df.id.values],
    'vector_rank_delta60': [f"rank(ts_delta(vec_avg({x}),60))" for x in cat_df.id.values],
    'vector_rank_backfill5': [f"rank(ts_backfill(vec_avg({x}),5))" for x in cat_df.id.values],
}

expression_list = expression_list_dict[type]
print(len(expression_list))

simulate_data_results_D1_rank(vec_avg(analyst))_
../backfill/INDTOP500/REVERSION_AND_MOMENTUM/[backfill_result]analyst_vector_D1_results.csv
1152

In [7]:
alpha_list = [
    ace.generate_alpha(
        x,
        alpha_type="REGULAR",
        region=params['region'],
        universe=params['universe'],
        delay=params['delay'],
        decay=5,
        test_period = "P2Y",
        neutralization =params['neutralization'],
        truncation = 0.05,
        pasteurization = "ON",
    ) for x in expression_list
]

alpha_list[0]

{'type': 'REGULAR',
 'settings': {'instrumentType': 'EQUITY',
  'region': 'IND',
  'universe': 'TOP500',
  'delay': 1,
  'decay': 5,
  'neutralization': 'REVERSION_AND_MOMENTUM',
  'truncation': 0.05,
  'pasteurization': 'ON',
  'testPeriod': 'P2Y',
  'unitHandling': 'VERIFY',
  'nanHandling': 'OFF',
  'maxTrade': 'OFF',
  'language': 'FASTEXPR',
  'visualization': False},
 'regular': 'rank(vec_avg(absolute_price_change_today_2))'}

In [11]:
import os
import time

k = 30
print(f"alpha_count={len(alpha_list)}, delay={delay}, doc={doc}, cat={cat}")
print(f"input_file_prefix={input_file_prefix}\noutput_file_path={output_file_path}")

for i in range(0, len(alpha_list), k):
    # if i<=2880: continue
    print(i, i+k, len(alpha_list))
    output_file = f'../backfill/{doc}/{input_file_prefix}{i}_{i+k}.csv'
    if os.path.exists(output_file):
        continue
    else:
        tmp_alpha_list = alpha_list[i:i+k]
        result = ace.simulate_alpha_list_multi(
            s,
            tmp_alpha_list,
            limit_of_concurrent_simulations=3,
            limit_of_multi_simulations=5,
        )
        not_empty_result = [r for r in result if r['alpha_id'] is not None]
        if len(not_empty_result)>0:
            output_df = hf.prettify_result(not_empty_result, clickable_alpha_id=False)
            output_df.to_csv(output_file, index=False)
    time.sleep(2)
print('Done')

alpha_count=1152, delay=D1, doc=INDTOP500/REVERSION_AND_MOMENTUM, cat=analyst
input_file_prefix=simulate_data_results_D1_rank(vec_avg(analyst))_
output_file_path=../backfill/INDTOP500/REVERSION_AND_MOMENTUM/[backfill_result]analyst_vector_D1_results.csv
0 30 1152
30 60 1152
60 90 1152
90 120 1152
120 150 1152
150 180 1152
180 210 1152
210 240 1152
240 270 1152
270 300 1152
300 330 1152
330 360 1152
360 390 1152
390 420 1152
420 450 1152
450 480 1152
480 510 1152
510 540 1152
540 570 1152
570 600 1152
600 630 1152
630 660 1152
660 690 1152

100%|██████████| 6/6 [06:22<00:00, 63.79s/it]

690 720 1152

100%|██████████| 6/6 [06:54<00:00, 69.16s/it]
/Users/bytedance/projects/my_wq_brain/ACE API [Gold]/helpful_functions.py:43: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  is_stats_df = pd.concat(list_of_is_stats).reset_index(drop=True)

720 750 1152

 33%|███▎      | 2/6 [56:03<1:52:07, 1681.83s/it]

ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

In [8]:
import os
import pandas as pd

print(output_file_path)

result_df = pd.DataFrame()
for f in os.listdir(f'../backfill/{doc}'):
    if f.startswith(input_file_prefix):
        # print(f)
        result_df = pd.concat([
            result_df,
            pd.read_csv( f'../backfill/{doc}/{f}')
        ], ignore_index=True)

print(result_df.shape)
result_df.sort_values('sharpe').to_csv(output_file_path, index=False)

../backfill/INDTOP500/REVERSION_AND_MOMENTUM/[backfill_result]analyst_vector_D1_results.csv
(600, 23)

# Rename

In [39]:
# 文件名重命名
for f in os.listdir(f'../backfill/{doc}'):
    if f.startswith('simulate_data_results_rankanalyst)_'):
        new_f = f[:22] + 'D1_rank(' + f[26:]
        old_path = f'../backfill/{doc}/{f}'
        new_path = f'../backfill/{doc}/{new_f}'
        print(old_path)
        print(new_path)
        # os.rename(old_path, new_path)

# Combine Alphas

In [3]:
import pandas as pd
factor_files = [
    '../backfill/EURTOPCS1600/[field_df]EUR_TOPCS1600_matrix_delay1.csv',
    '../backfill/EURTOPCS1600/[field_df]EUR_TOPCS1600_vector_delay1.csv',
]
factor_df = pd.concat([ pd.read_csv(f) for f in factor_files ])
print(factor_df.shape)
factor_df.head()

(22474, 22)

,Unnamed: 0,id,description,dataset,category,subcategory,region,delay,universe,type,...,userCount,alphaCount,pyramidMultiplier,themes,dataset_id,dataset_name,category_id,category_name,subcategory_id,subcategory_name
0,0,anl10_cpxff,Capital expenditures - field format,"{'id': 'analyst10', 'name': 'Performance-Weigh...","{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",EUR,1,TOPCS1600,MATRIX,...,1,1,1.4,[],analyst10,Performance-Weighted Analyst Estimates,analyst,Analyst,analyst-analyst-estimates,Analyst Estimates
1,1,anl10_cpxfy1_consensus,Consensus estimate value for capital expenditu...,"{'id': 'analyst10', 'name': 'Performance-Weigh...","{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",EUR,1,TOPCS1600,MATRIX,...,0,0,1.4,[],analyst10,Performance-Weighted Analyst Estimates,analyst,Analyst,analyst-analyst-estimates,Analyst Estimates
2,2,anl10_cpxfy1_pred_surps_v0,Predicted surprise version 0 for capital expen...,"{'id': 'analyst10', 'name': 'Performance-Weigh...","{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",EUR,1,TOPCS1600,MATRIX,...,0,0,1.4,[],analyst10,Performance-Weighted Analyst Estimates,analyst,Analyst,analyst-analyst-estimates,Analyst Estimates
3,3,anl10_cpxfy1_pred_surps_v1,Predicted surprise version 1 for capital expen...,"{'id': 'analyst10', 'name': 'Performance-Weigh...","{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",EUR,1,TOPCS1600,MATRIX,...,1,1,1.4,[],analyst10,Performance-Weighted Analyst Estimates,analyst,Analyst,analyst-analyst-estimates,Analyst Estimates
4,4,anl10_cpxfy1_pred_surps_v2,Predicted surprise version 2 for capital expen...,"{'id': 'analyst10', 'name': 'Performance-Weigh...","{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",EUR,1,TOPCS1600,MATRIX,...,0,0,1.4,[],analyst10,Performance-Weighted Analyst Estimates,analyst,Analyst,analyst-analyst-estimates,Analyst Estimates

In [4]:
def extract_last_parentheses(text):
    """
    提取字符串中最后一个括号内的内容
    参数:
        text: 包含括号的字符串
    返回:
        最后一个括号内的内容，如果找不到括号返回None
    """
    # 查找最后一个 '(' 和最后一个 ')'
    left_idx = text.rfind('(')
    right_idx = text.find(')')
    # 确保找到两个括号且左括号在右括号之前
    if left_idx != -1 and right_idx != -1 and left_idx < right_idx:
        alpha = text[left_idx+1: right_idx].strip()
        alpha = alpha.split(',')[0].strip()
        alpha = alpha.strip('-')
        return alpha
    return None

file_ret_dict = {
    'rank': [
                '../backfill/EURTOPCS1600/COUNTRY/[backfill_result]analyst_matrix_D1_results.csv',
                '../backfill/EURTOPCS1600/COUNTRY/[backfill_result]analyst_vector_D1_results.csv',
                '../backfill/EURTOPCS1600/COUNTRY/[backfill_result]earnings_vector_D1_results.csv',
                '../backfill/EURTOPCS1600/COUNTRY/[backfill_result]fundamental_matrix_D1_results.csv',
                '../backfill/EURTOPCS1600/COUNTRY/[backfill_result]fundamental_vector_D1_results.csv',
                '../backfill/EURTOPCS1600/COUNTRY/[backfill_result]imbalance_matrix_D1_results.csv',
                '../backfill/EURTOPCS1600/COUNTRY/[backfill_result]insiders_vector_D1_results.csv',
                '../backfill/EURTOPCS1600/COUNTRY/[backfill_result]model_matrix_D1_results.csv',
                '../backfill/EURTOPCS1600/COUNTRY/[backfill_result]model_vector_D1_results.csv',
                '../backfill/EURTOPCS1600/COUNTRY/[backfill_result]news_matrix_D1_results.csv',
                '../backfill/EURTOPCS1600/COUNTRY/[backfill_result]option_matrix_D1_results.csv',
                '../backfill/EURTOPCS1600/COUNTRY/[backfill_result]option_vector_D1_results.csv',
                '../backfill/EURTOPCS1600/COUNTRY/[backfill_result]other_matrix_D1_results.csv',
                '../backfill/EURTOPCS1600/COUNTRY/[backfill_result]other_vector_D1_results.csv',
                '../backfill/EURTOPCS1600/COUNTRY/[backfill_result]pv_matrix_D1_results.csv',
                '../backfill/EURTOPCS1600/COUNTRY/[backfill_result]pv_vector_D1_results.csv',
                '../backfill/EURTOPCS1600/COUNTRY/[backfill_result]risk_matrix_D1_results.csv',
                '../backfill/EURTOPCS1600/COUNTRY/[backfill_result]risk_vector_D1_results.csv',
                '../backfill/EURTOPCS1600/COUNTRY/[backfill_result]sentiment_matrix_D1_results.csv',
                '../backfill/EURTOPCS1600/COUNTRY/[backfill_result]sentiment_vector_D1_results.csv',
                '../backfill/EURTOPCS1600/COUNTRY/[backfill_result]shortinterest_vector_D1_results.csv',
                '../backfill/EURTOPCS1600/COUNTRY/[backfill_result]socialmedia_matrix_D1_results.csv',
                '../backfill/EURTOPCS1600/COUNTRY/[backfill_result]socialmedia_vector_D1_results.csv',
             ],
    'delta5_rank': [],
    'delta60_rank': [],
    'backfill60_rank': [],
    'negetive_candidate': []
}

final_values_df = pd.DataFrame()
for type in file_ret_dict:
    files = file_ret_dict[type]
    if len(files)>0:
        values_df = pd.concat([
            pd.read_csv(f).drop_duplicates().assign(file_name=f) for f in files
        ])
        print(type, values_df.shape)
        values_df['alpha'] = values_df['expression'].apply(extract_last_parentheses)
        final_values_df = pd.concat([final_values_df, values_df])

final_values_df = pd.merge(final_values_df,
                           factor_df[['id','category_id','dataset_id']],
                           how='left', left_on='alpha', right_on='id')
print('final_values_df', final_values_df.shape)

rank (20440, 26)
final_values_df (20440, 30)

In [5]:
# Save final_values_df to CSV file
need_datasets = [   'analyst11','analyst16','analyst39','analyst40','analyst44','analyst48','analyst9',
    'fundamental1','fundamental65','fundamental72',
    'model135','model138','model176','model211','model216','model31','model37','model53','model354',
    'news17','news20','news31','news46','news48','news50','news7','news79','news23','news21','news29',
    'other401','other432','other460','other696','other567','other384','other699',
    'earningscall_sentiment',
    'analyst45',
    'fundamental25'
]
# final_values_df[final_values_df['dataset_id'].isin(need_datasets)].to_csv('../backfill/EURTOPCS1600/COUNTRY/[backfill_result_wide_table]D1_results.csv')

final_values_df.to_csv('../backfill/EURTOPCS1600/COUNTRY/[backfill_result_wide_table]D1_results.csv')

In [64]:
final_values_df[(final_values_df['long_count']>=100)]

Empty DataFrame
Columns: [pnl, book_size, long_count, short_count, turnover, returns, drawdown, margin, sharpe, fitness, start_date, investability_constrained, alpha_id, expression, concentrated_weight, high_turnover, low_2y_sharpe, low_fitness, low_robust_universe_sharpe, low_sharpe, low_sub_universe_sharpe, low_turnover, matches_pyramid, matches_themes, file_name, alpha, id, category_id]
Index: []

[0 rows x 28 columns]

In [269]:
final_values_df.columns

Index(['pnl', 'book_size', 'long_count', 'short_count', 'turnover', 'returns',
       'drawdown', 'margin', 'sharpe', 'fitness', 'start_date',
       'investability_constrained', 'alpha_id', 'expression',
       'concentrated_weight', 'high_turnover', 'low_2y_sharpe', 'low_fitness',
       'low_sharpe', 'low_sub_universe_sharpe', 'low_turnover',
       'matches_pyramid', 'matches_themes', 'file_name', 'alpha', 'id',
       'category_id'],
      dtype='object')

In [66]:
final_values_df[
                (final_values_df['long_count']>=100)&
                (final_values_df['low_2y_sharpe']=='PASS')&
                (final_values_df['low_robust_universe_sharpe']=='PASS')&
                (final_values_df['low_fitness']=='PASS')&
                (final_values_df['low_sub_universe_sharpe']=='PASS')&
                (final_values_df['sharpe']>1)
][['file_name','alpha_id','category_id','expression']]

,file_name,alpha_id,category_id,expression
1735,../backfill/IND/other_matrix_results.csv,1Y5vnP7M,other,rank(oth335_combined_all_region_hedge)
1736,../backfill/IND/other_matrix_results.csv,N1oM53be,other,rank(oth335_combined_all_region_mind)
4004,../backfill/IND/analyst_vector_results.csv,88qEZ3xX,analyst,rank(vec_avg(anl44_best_eps_4wk_chg))
4005,../backfill/IND/analyst_vector_results.csv,j2QxQ3VO,analyst,rank(vec_avg(eps_estimate_4wk_change))
5679,../backfill/IND/model_matrix_results.csv,P0eNzNZL,model,rank(forecasted_surprise_year2_revenue)
...,...,...,...,...
9085,../backfill/IND/negative_candidates_results.csv,RRXo13k1,model,rank(-mdl26_score)
9086,../backfill/IND/negative_candidates_results.csv,Jjlkx6Z2,risk,rank(-ts_delta(residualized_return_india_equit...
9087,../backfill/IND/negative_candidates_results.csv,wp6AEmJx,model,rank(-star_arm_score_5)
9088,../backfill/IND/negative_candidates_results.csv,e7AP0G9d,risk,rank(-residualized_return_india_top500_equity)
9089,../backfill/IND/negative_candidates_results.csv,gJv5QnEe,risk,rank(-ts_delta(residualized_return_india_top50...

# generate_merge_df

In [26]:
for category in final_values_df['category_id'].unique():
    # if category in ('pv'):
    if category in ('other'):
        cat_final_values_df = final_values_df[final_values_df['category_id'] == category]
        q_cat_final_values_df = cat_final_values_df[
                                        (cat_final_values_df['long_count']>=100) &
                                        (cat_final_values_df['sharpe']>1.2)
                                    ]
        print(category, q_cat_final_values_df.shape)

        import itertools
        expressions = q_cat_final_values_df['expression'].tolist()
        combinations = list(itertools.combinations(expressions, 2))
        print(f"总共生成 {len(combinations)} 个组合")

        # 迭代所有组合
        combine_expressions1 = [f'a={expr1};b={expr2};a+b'                                for i, (expr1, expr2) in enumerate(combinations)]
        combine_expressions2_1 = [f'a={expr1};b={expr2};ts_regression(a,b,20,rettype=1)'  for i, (expr1, expr2) in enumerate(combinations)]
        combine_expressions2_2 = [f'a={expr2};b={expr1};ts_regression(a,b,20,rettype=1)'  for i, (expr1, expr2) in enumerate(combinations)]
        combine_expressions3_1 = [f'a={expr1};b={expr2};ts_regression(a,b,20,rettype=2)'  for i, (expr1, expr2) in enumerate(combinations)]
        combine_expressions3_2 = [f'a={expr2};b={expr1};ts_regression(a,b,20,rettype=2)'  for i, (expr1, expr2) in enumerate(combinations)]
        combine_expressions4_1 = [f'trade_when({expr1}>0.5,{expr2},{expr1}<=0.5)'         for i, (expr1, expr2) in enumerate(combinations)]
        combine_expressions4_2 = [f'trade_when({expr2}>0.5,{expr1},{expr2}<=0.5)'         for i, (expr1, expr2) in enumerate(combinations)]
        combine_expressions = combine_expressions1 + combine_expressions2_1 + combine_expressions3_1 + combine_expressions4_1 + combine_expressions2_2 + combine_expressions3_2 + combine_expressions4_2
        alpha_list = [
            ace.generate_alpha(
                x,
                alpha_type="REGULAR",
                region="IND",
                universe="TOP500",
                delay=1,
                decay=5,
                test_period = "P2Y",
                neutralization = "INDUSTRY",
                truncation = 0.05,
                pasteurization = "ON",
            ) for x in combine_expressions
        ]
print(len(alpha_list))

other (23, 28)
总共生成 253 个组合
759

In [26]:
import os
import time

k = 30
for i in range(0, len(alpha_list), k):
    print(i, i+k)
    output_file = f'../backfill/IND/[simulate_data_results]other_combine_factors_{i}_{i+k}.csv'
    if os.path.exists(output_file):
        continue
    else:
        tmp_alpha_list = alpha_list[i:i+k]
        result = ace.simulate_alpha_list_multi(
            s,
            tmp_alpha_list,
            limit_of_concurrent_simulations=3,
            limit_of_multi_simulations=5,
        )
        not_empty_result = [r for r in result if r['alpha_id'] is not None]
        if len(not_empty_result)>0:
            output_df = hf.prettify_result(not_empty_result, clickable_alpha_id=False)
            output_df.to_csv(output_file, index=False)
    time.sleep(2)
print('Done')

0 30
30 60

  0%|          | 0/6 [00:05<?, ?it/s]

KeyboardInterrupt:

In [24]:
import os
import pandas as pd

result_df = pd.DataFrame()
for f in os.listdir(f'../backfill/IND'):
    if f.startswith(f'[simulate_data_results]pv_combine_factors_'):
        # print(f)
        result_df = pd.concat([
            result_df,
            pd.read_csv( f'../backfill/IND/{f}')
        ], ignore_index=True)

print(result_df.shape)
# result_df.sort_values('sharpe').to_csv(f'../backfill/{doc}/{cat}_vector_{delay}_results.csv', index=False)
result_df.sort_values('sharpe').to_csv(f'../backfill/IND/[simulate_data_results]other_combine_factors_results.csv', index=False)

(315, 24)

# generate_negative_df

In [33]:
expression_list = ['(-'.join(expr.split('(',1)) for expr in final_values_df[
                # (final_values_df['low_2y_sharpe']=='PASS')&
                # (final_values_df['low_robust_universe_sharpe']=='PASS')&
                # (final_values_df['low_fitness']=='PASS')&
                # (final_values_df['low_sub_universe_sharpe']=='PASS')&
                (# (final_values_df['sharpe']>1)|
                 (final_values_df['sharpe']<-1.5)
                )
]['expression']]

alpha_list = [
    ace.generate_alpha(
        x,
        alpha_type="REGULAR",
        region="IND",
        universe="TOP500",
        delay=1,
        decay=5,
        test_period = "P2Y",
        neutralization = "INDUSTRY",
        truncation = 0.05,
        pasteurization = "ON",
    ) for x in expression_list
]

alpha_list[0]

{'type': 'REGULAR',
 'settings': {'instrumentType': 'EQUITY',
  'region': 'IND',
  'universe': 'TOP500',
  'delay': 1,
  'decay': 5,
  'neutralization': 'INDUSTRY',
  'truncation': 0.05,
  'pasteurization': 'ON',
  'testPeriod': 'P2Y',
  'unitHandling': 'VERIFY',
  'nanHandling': 'OFF',
  'maxTrade': 'OFF',
  'language': 'FASTEXPR',
  'visualization': False},
 'regular': 'rank(-fnd17_pr5dayprc)'}

In [34]:
expression_list

['rank(-fnd17_pr5dayprc)',
 'rank(-fnd17_chpctpricewtd)',
 'rank(-fnd17_pr1dayprc)',
 'rank(-idiosyncratic_return_fraction)',
 'rank(-pv47_spret)',
 'rank(-pv47_for_statssimple_only_spret)',
 'rank(-vec_avg(region_exposure_percent_minimum))',
 'rank(-vec_avg(max_trade_price))',
 'rank(-vec_avg(insd5_nm_kor))',
 'rank(-headline_mention_count_2)',
 'rank(-oth532_global_daily_specificreturn)',
 'rank(-oth532_emerging_daily_specificreturn)',
 'rank(-oth532_asia_ase2_daily_specificreturn)',
 'rank(-vec_avg(oth696_lawsuit_positive))',
 'rank(-vec_avg(rd_negative_event_count))',
 'rank(-vec_avg(oth696_investments_negative))',
 'rank(-vec_avg(oth696_productdesignlifecyclemanagement_positive))',
 'rank(-vec_avg(oth696_managementlegalregulatoryframework_negative))',
 'rank(-vec_avg(oth696_geostability_positive))',
 'rank(-vec_avg(oth696_customerwelfare_positive))',
 'rank(-vec_avg(leg1_spread_value))',
 'rank(-vec_avg(oth696_stockprice_negative))',
 'rank(-vec_avg(leg2_aggregate_notional_quantity))',
 'rank(-vec_avg(oth532_spret))',
 'rank(-vec_avg(oth696_airquality_positive))',
 'rank(-snt21_4neg_max)',
 'rank(-snt21_5pos_max)',
 'rank(-snt21_5pos_conf_up)',
 'rank(-snt21_4neg_mean)',
 'rank(-snt21_5pos_conf_low)',
 'rank(-snt21_4neg_median)',
 'rank(-snt21_4neg_conf_up)',
 'rank(-snt21_5pos_mean)',
 'rank(-vec_avg(other_executive_numeric_word_ratio_presentation))',
 'rank(-vec_avg(reference_index_currency_3))',
 'rank(-vec_avg(anl4_detailrecv4_est))',
 'rank(-vec_avg(anl83_ceo_neg_logit_qa))',
 'rank(-vec_avg(eps_estimate_4wk_down_count))',
 'rank(-vec_avg(anl44_best_eps_4wk_dn))',
 'rank(-vec_avg(pretaxprofit_estimates_down_4w))',
 'rank(-residualized_return_india_top500_equity)',
 'rank(-residualized_return_india_equity_universe)',
 'rank(-residualized_return_india_top200_equity)',
 'rank(-rsk68_residual_return)',
 'rank(-residualized_return_india_single_stock_futures)',
 'rank(-star_arm_score_5)',
 'rank(-mdl26_score)',
 'rank(-score_avg_5d)',
 'rank(-mdl26_sma_arm_score_5)',
 'rank(-composite_score_qsg_india)',
 'rank(-three_month_revision_fy1_earnings_india)',
 'rank(-mdl177_indrelrtn5d_)',
 'rank(-three_month_revision_fy2_earnings_india)',
 'rank(-mdl177_fc_epsrm)',
 'rank(-mdl26_rcmmndtn_mn_chng_90)',
 'rank(-avg_change_analyst_recommendation_90d)',
 'rank(-mdl177_chgepsp)',
 'rank(-mdl177_fc_numrevy1)',
 'rank(-star_arm_rec_mean_prior7)',
 'rank(-avg_change_analyst_recommendation_7d)',
 'rank(-mdl26_rcmmndtn_mn_chng_7)',
 'rank(-mdl177_chgnpm)',
 'rank(-mdl177_pctchgeps)',
 'rank(-mdl177_fc_rev3y1)',
 'rank(-mdl26_num_downgrades_7)',
 'rank(-count_analyst_recommendation_downgrades_7d)',
 'rank(-avg_change_analyst_recommendation_30d)',
 'rank(-mdl26_sm_rcmmndtn_mn_chng_30)',
 'rank(-vec_avg(mdl135_d3_if))',
 'rank(-vec_avg(mdl135_d3_ivn))',
 'rank(-vec_avg(mdl135_d3_iv))',
 'rank(-vec_avg(mdl135_d5_if))',
 'rank(-vec_avg(mdl135_d5_icc))',
 'rank(-vec_avg(mdl135_d5_bb))',
 'rank(-vec_avg(mdl135_d5_iv))',
 'rank(-vec_avg(mdl135_d3_icc))',
 'rank(-vec_avg(mdl135_d3_fmc))',
 'rank(-vec_avg(mdl135_d3_lda))',
 'rank(-vec_avg(mdl135_d3_bb))',
 'rank(-vec_avg(mdl135_d3_vbo))',
 'rank(-vec_avg(mdl135_d3_tpv))',
 'rank(-vec_avg(mdl135_d3_isr))',
 'rank(-vec_avg(mdl135_d01_bb))',
 'rank(-vec_avg(mdl135_d3_vme))',
 'rank(-vec_avg(mdl135_d5_oa))',
 'rank(-vec_avg(mdl135_vlc))',
 'rank(-vec_avg(mdl135_d01_icc))',
 'rank(-vec_avg(mdl135_d7_oc))',
 'rank(-vec_avg(mdl135_d3_ifm))',
 'rank(-vec_avg(mdl135_d5_fmc))',
 'rank(-vec_avg(mdl135_d3ntr))',
 'rank(-vec_avg(mdl135_d5_vbo))',
 'rank(-vec_avg(mdl135_d5_isr))',
 'rank(-vec_avg(mdl135_d5ntr))',
 'rank(-vec_avg(mdl135_macd_3d))',
 'rank(-vec_avg(mdl135_d5_lda))',
 'rank(-vec_avg(mdl135_d6_oc))',
 'rank(-vec_avg(mdl135_macd_2d))',
 'rank(-vec_avg(mdl135_d8_oc))',
 'rank(-vec_avg(mdl135_d5_vme))',
 'rank(-vec_avg(mdl135_willimsr_5d))',
 'rank(-vec_avg(mdl135_d3_oa))',
 'rank(-vec_avg(mdl135_d5_ivn))',
 'rank(-vec_avg(mdl135_macd_4d))',
 'rank(-vec_avg(mdl135_d01_if))',
 'rank(-vec_avg(mdl135_macd_1d))',
 'rank(-vec_avg(triple_ema_rate_change_3d))',
 'rank(-vec_avg(mdl135_willimsr_10d))',
 'rank(-vec_avg(mdl135_d5_oc))',
 'rank(-vec_avg(mdl135_willimsr_3d))',
 'rank(-vec_avg(mdl135_d04_isrs))',
 'rank(-vec_avg(mdl135_d02_isrs))',
 'rank(-vec_avg(mdl135_d01_iv))',
 'rank(-vec_avg(mdl135_d01_isrs))',
 'rank(-vec_avg(mdl135_d01_oa))',
 'rank(-vec_avg(mdl135_d3_oc))',
 'rank(-vec_avg(mdl135_ou))',
 'rank(-vec_avg(mdl135_d5_ifm))',
 'rank(-vec_avg(mdl135_d2_ou))',
 'rank(-vec_avg(mdl135_d02_bb))',
 'rank(-vec_avg(mdl135_d01_vme))',
 'rank(-vec_avg(mdl135_ist))',
 'rank(-vec_avg(mdl135_d2_oc))',
 'rank(-vec_avg(mdl135_d4_oc))',
 'rank(-vec_avg(mdl135_d3_os))',
 'rank(-vec_avg(mdl135_d01_isr))',
 'rank(-vec_avg(mdl135_d02_icc))',
 'rank(-ts_delta(idiosyncratic_return_fraction, 5))',
 'rank(-ts_delta(pv47_spret, 5))',
 'rank(-ts_delta(pv47_for_statssimple_only_spret, 5))',
 'rank(-ts_delta(session_1430to1430_total_traded_volume, 5))',
 'rank(-ts_delta(session_1430to1430_initial_trade_price, 5))',
 'rank(-ts_delta(session_1430to1430_min_trade_price, 5))',
 'rank(-ts_delta(session_1430to1430_volume_weighted_avg_price, 5))',
 'rank(-ts_delta(session_1430to1430_final_trade_price, 5))',
 'rank(-ts_delta(session_1430to1430_max_trade_price, 5))',
 'rank(-ts_delta(session_1430to1430_market_value, 5))',
 'rank(-ts_delta(mws52_sentences_in_qa,5))',
 'rank(-ts_delta(mws52_conference_call_participants,5))',
 'rank(-ts_delta(mws52_pparagraphs_in_qa,5))',
 'rank(-ts_delta(mws52_chars_in_qa,5))',
 'rank(-ts_delta(event_frequency_label,5))',
 'rank(-ts_delta(mws52_questions_in_qa,5))',
 'rank(-ts_delta(mws52_talks_in_qa,5))',
 'rank(-ts_delta(mws52_words_in_qa,5))',
 'rank(-ts_delta(mws52_questions_in_presentation,5))',
 'rank(- ts_delta( fnd17_chpctpricewtd, 60) )',
 'rank(- ts_delta( fnd17_pr1dayprc, 60) )',
 'rank(- ts_delta( fnd4_chinascope_secmap, 60) )',
 'rank(- ts_delta( fnd17_ttmdebteps, 60) )',
 'rank(- ts_delta( fnd17_pr5dayprc, 60) )',
 'rank(-ts_delta(vec_avg(operator_forward_looking_sentiment_presentation),60))',
 'rank(-ts_delta(vec_avg(relative_index_return_percent_limited),60))',
 'rank(-ts_delta(vec_avg(success_likelihood_score_4),60))',
 'rank(-ts_delta(vec_avg(mean_daily_relative_performance),60))',
 'rank(-ts_delta(vec_avg(analyst_positive_sentiment_logit_presentation),60))',
 'rank(-ts_delta(vec_avg(analyst_negative_sentiment_logit_presentation),60))',
 'rank(-ts_delta(vec_avg(relative_percent_return_today_limited),60))',
 'rank(-ts_delta(vec_avg(anl45_limited_tot_ret),60))',
 'rank(-ts_delta(vec_avg(anl45_limited_treynor_ratio),60))',
 'rank(-ts_delta(vec_avg(anl45_limited_tot_ret_wo_fx),60))',
 'rank(-ts_delta(vec_avg(anl45_limited_stock_ret_per),60))',
 'rank(-ts_delta(vec_avg(benchmark_index_return_percent_limited),60))',
 'rank(-ts_delta(vec_avg(anl45_limited_bias_weighted_ret),60))',
 'rank(-ts_delta(vec_avg(anl83_serp_erf),60))',
 'rank(-ts_delta(vec_avg(anl83_ceo_pos_logit_qa),60))',
 'rank(-ts_delta(residualized_return_india_top500_equity,60))',
 'rank(-ts_delta(residualized_return_india_equity_universe,60))',
 'rank(-ts_delta(rsk68_residual_return,60))',
 'rank(-ts_delta(residualized_return_india_top200_equity,60))',
 'rank(-ts_delta(residualized_return_india_single_stock_futures,60))',
 'rank(-ts_backfill(oth532_asia_ase2_daily_specificreturn,60))',
 'rank(-ts_backfill(oth532_global_daily_specificreturn,60))',
 'rank(-ts_backfill(oth532_emerging_daily_specificreturn,60))']

In [36]:
import os
import time

k = 30
for i in range(0, len(alpha_list), k):
    print(i, i+k)
    output_file = f'../backfill/IND/simulate_data_results_negative_candidates_{i}_{i+k}.csv'
    if os.path.exists(output_file):
        continue
    else:
        tmp_alpha_list = alpha_list[i:i+k]
        result = ace.simulate_alpha_list_multi(
            s,
            tmp_alpha_list,
            limit_of_concurrent_simulations=3,
            limit_of_multi_simulations=5,
        )
        not_empty_result = [r for r in result if r['alpha_id'] is not None]
        if len(not_empty_result)>0:
            output_df = hf.prettify_result(not_empty_result, clickable_alpha_id=False)
            output_df.to_csv(output_file, index=False)
    time.sleep(2)

print('Done')

0 30
30 60

100%|██████████| 6/6 [07:21<00:00, 73.51s/it]

60 90

100%|██████████| 6/6 [07:45<00:00, 77.56s/it]

90 120

100%|██████████| 6/6 [11:12<00:00, 112.10s/it]

120 150

100%|██████████| 6/6 [10:14<00:00, 102.34s/it]

150 180

100%|██████████| 5/5 [05:59<00:00, 71.89s/it]

Done

In [37]:
import os
import pandas as pd

result_df = pd.DataFrame()
for f in os.listdir(f'../backfill/IND'):
    if f.startswith(f'simulate_data_results_negative_candidates_'):
    # if f.startswith(f'simulate_data_results_{delay}_rank({cat})_'):
        # print(f)
        result_df = pd.concat([
            result_df,
            pd.read_csv( f'../backfill/IND/{f}' )
        ], ignore_index=True)
print(result_df.shape)

result_df.sort_values('sharpe').to_csv(f'../backfill/IND/negative_candidates_results.csv', index=False)

(174, 23)