In [5]:
import os
!pip install -r requirements.txt

[notice] A new release of pip is available: 24.3.1 -> 25.3
[notice] To update, run: pip install --upgrade pip
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

In [1]:
import ace_lib as ace
import helpful_functions as hf
import pandas as pd
import plotly.express as px
from tqdm import tqdm

In [2]:
s = ace.start_session()
ace.check_session_timeout(s)

14398.739098

In [71]:
s = ace.check_session_and_relogin(s)

In [43]:
# datasets_df = ace.get_datasets(
#     s,
#     region='IND',
#     universe='TOP500',
#     delay=1,
#     theme='false'
# )
datasets_df = ace.get_datasets(
    s,
    region='CHN',
    universe='TOP2000U',
    delay=1,
)
# datasets_df = ace.get_datasets(
#     s,
#     region='EUR',
#     universe='TOPCS1600',
#     delay=1,
# )
print(len(datasets_df))
datasets_df.head()

55

,id,name,description,category,subcategory,region,delay,universe,dateCoverage,coverage,...,userCount,alphaCount,fieldCount,pyramidMultiplier,themes,researchPapers,category_id,category_name,subcategory_id,subcategory_name
0,analyst10,Performance-Weighted Analyst Estimates,"This dataset provides ""smart estimates,"" which...","{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",CHN,1,TOP2000U,1.0,0.6560,...,69,156,515,1.8,[],"[{'type': 'discussion', 'title': 'Getting star...",analyst,Analyst,analyst-analyst-estimates,Analyst Estimates
1,analyst11,ESG scores,This dataset provides a comprehensive mapping ...,"{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-esg', 'name': 'ESG'}",CHN,1,TOP2000U,1.0,0.5079,...,0,0,126,1.8,[],"[{'type': 'discussion', 'title': 'Getting star...",analyst,Analyst,analyst-esg,ESG
2,analyst14,Estimations of Key Fundamentals,This dataset reports many items from financial...,"{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",CHN,1,TOP2000U,1.0,0.5000,...,231,793,308,1.8,[],"[{'type': 'discussion', 'title': 'Getting star...",analyst,Analyst,analyst-analyst-estimates,Analyst Estimates
3,analyst45,Analyst Trade Ideas,This dataset provides a comprehensive mapping ...,"{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",CHN,1,TOP2000U,1.0,1.0000,...,4,4,60,1.8,[],"[{'type': 'discussion', 'title': 'Getting star...",analyst,Analyst,analyst-analyst-estimates,Analyst Estimates
4,analyst69,Fundamental Analyst Estimates,This dataset is a type of analyst dataset that...,"{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",CHN,1,TOP2000U,1.0,0.7661,...,387,1559,596,1.8,[],"[{'type': 'discussion', 'title': 'Getting star...",analyst,Analyst,analyst-analyst-estimates,Analyst Estimates

In [44]:
"""
1	8  Dec - 14 Dec	| Fundamental, Earnings, Short Interest, PV, Broker
2	15 Dec - 21 Dec	| Insiders, Sentiment, News, Other, Option
3	22 Dec - 28 Dec	| Institutions, Analyst, Risk
4	29 Dec - 4  Jan	| Macro, Model
"""

dataset_ids = []
for cat in datasets_df['category_id'].unique():
    cat_df = datasets_df[datasets_df['category_id']==cat]
    print(cat, len(cat_df))
    dataset_ids += cat_df['id'].tolist()
    print(cat_df['id'].tolist())
    print()
print(len(dataset_ids))

analyst 5
['analyst10', 'analyst11', 'analyst14', 'analyst45', 'analyst69']

fundamental 5
['fundamental23', 'fundamental27', 'fundamental4', 'fundamental5', 'fundamental6']

macro 2
['macro61', 'other551']

model 15
['model135', 'model138', 'model14', 'model144', 'model170', 'model175', 'model207', 'model243', 'model26', 'model291', 'model307', 'model31', 'model36', 'model37', 'model39']

news 9
['news11', 'news21', 'news29', 'news38', 'news46', 'news50', 'news7', 'news76', 'news79']

other 8
['other315', 'other370', 'other496', 'other545', 'other546', 'other561', 'other592', 'other715']

pv 7
['pv1', 'pv106', 'pv173', 'pv25', 'pv27', 'pv29', 'pv30']

risk 1
['risk72']

sentiment 1
['sentiment27']

shortinterest 1
['shortinterest5']

socialmedia 1
['socialmedia12']

55

In [45]:
import time
# res_df = ace.get_datafields(
#     s,
#     region='EUR',
#     universe='TOPCS1600',
#     delay=1,
# )
res_df = ace.get_datafields(
    s,
    region='CHN',
    universe='TOP2000U',
    delay=1,
)
res_df = res_df[res_df['type']=='VECTOR']
print(res_df.columns)
print(res_df.shape)
res_df.head()

2026-03-01 12:28:18,306 - ace - INFO - Getting fields for: region=CHN, delay=1, universe=TOP2000U

Index(['id', 'description', 'dataset', 'category', 'subcategory', 'region',
       'delay', 'universe', 'type', 'dateCoverage', 'coverage', 'userCount',
       'alphaCount', 'pyramidMultiplier', 'themes', 'dataset_id',
       'dataset_name', 'category_id', 'category_name', 'subcategory_id',
       'subcategory_name'],
      dtype='object')
(3097, 21)

,id,description,dataset,category,subcategory,region,delay,universe,type,dateCoverage,...,userCount,alphaCount,pyramidMultiplier,themes,dataset_id,dataset_name,category_id,category_name,subcategory_id,subcategory_name
0,absolute_price_change_today_2,Change in security price since the previous da...,"{'id': 'analyst45', 'name': 'Analyst Trade Ide...","{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",CHN,1,TOP2000U,VECTOR,1.0000,...,1,1,1.8,[],analyst45,Analyst Trade Ideas,analyst,Analyst,analyst-analyst-estimates,Analyst Estimates
27,active_notional_value_leg1,Monetary notional amount effective for leg 1 o...,"{'id': 'other315', 'name': 'Equity Swap Data'}","{'id': 'other', 'name': 'Other'}","{'id': 'other-aiml-data', 'name': 'AI/ML Data'}",CHN,1,TOP2000U,VECTOR,0.9499,...,0,0,1.7,[],other315,Equity Swap Data,other,Other,other-aiml-data,AI/ML Data
28,adjusted_bias_return,"Return adjusted for bias, often used for non-f...","{'id': 'analyst45', 'name': 'Analyst Trade Ide...","{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",CHN,1,TOP2000U,VECTOR,1.0000,...,2,2,1.8,[],analyst45,Analyst Trade Ideas,analyst,Analyst,analyst-analyst-estimates,Analyst Estimates
32,aggregate_realized_unrealized_return,Sum of realized and unrealized returns for the...,"{'id': 'analyst45', 'name': 'Analyst Trade Ide...","{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",CHN,1,TOP2000U,VECTOR,1.0000,...,0,0,1.8,[],analyst45,Analyst Trade Ideas,analyst,Analyst,analyst-analyst-estimates,Analyst Estimates
33,aggregate_return_excluding_fx,Total return excluding foreign exchange effects.,"{'id': 'analyst45', 'name': 'Analyst Trade Ide...","{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",CHN,1,TOP2000U,VECTOR,1.0000,...,0,0,1.8,[],analyst45,Analyst Trade Ideas,analyst,Analyst,analyst-analyst-estimates,Analyst Estimates

In [48]:
# res_df.to_csv('../backfill/EUR/[field_df]EUR_TOPCS1600_vector_delay1.csv')
# res_df.to_csv('../backfill/[2nd]field_df_IND_TOP500_delay1_vector.csv')
# res_df.to_csv('../backfill/[2nd]field_df_IND_TOP500_delay1_matrix.csv')
# res_df.to_csv('../backfill/week3/matrix_field_df_IND_TOP500_delay1.csv')
# res_df.to_csv('../backfill/week3/vector_field_df_IND_TOP500_delay1.csv')
# res_df.to_csv('../backfill/week4/matrix_field_df_IND_TOP500_delay1.csv')
# res_df.to_csv('../backfill/week4/vector_field_df_IND_TOP500_delay1.csv')
# res_df.to_csv('../backfill/ASI/matrix_field_df_ASI_MINVOL1M_delay1.csv')
# res_df.to_csv('../backfill/ASI/vector_field_df_ASI_MINVOL1M_delay1.csv')
# res_df.to_csv('../backfill/EUR/matrix_field_df_EUR_TOP2500_delay0.csv')
# res_df.to_csv('../backfill/GLB/vector_field_df_EUR_TOP2500_delay0.csv')
# res_df.to_csv('../backfill/AMR/[field_df]AMR_TOP600_matrix_delay1.csv')
# res_df.to_csv('../backfill/AMR/[field_df]AMR_TOP600_vector_delay1.csv')
# res_df.to_csv('../backfill/AMR/[field_df]AMR_TOP600_matrix_delay0.csv')

# res_df.to_csv('../backfill/CHNTOP2000U/[field_df]CHN_TOP2000U_vector_delay1.csv')
# res_df = pd.read_csv('../backfill/EUR/[field_df]EUR_TOPCS1600_vector_delay1.csv',index_col=0).drop_duplicates()
# res_df = pd.read_csv('../backfill/EUR/[field_df]EUR_TOPCS1600_matrix_delay1.csv',index_col=0).drop_duplicates()
res_df = pd.read_csv('../backfill/GLB/[field_df]GLB_TOP3000_matrix_delay1.csv',index_col=0).drop_duplicates()
# res_df = pd.read_csv('../backfill/GLB/[field_df]GLB_TOP3000_vector_delay1.csv',index_col=0).drop_duplicates()
# res_df = pd.read_csv('../backfill/AMR/[field_df]AMR_TOP600_vector_delay1.csv',index_col=0)
# res_df = pd.read_csv('../backfill/AMR/[field_df]AMR_TOP600_matrix_delay1.csv',index_col=0)

print(res_df.shape)
res_df

(13064, 21)

,id,description,dataset,category,subcategory,region,delay,universe,type,dateCoverage,...,userCount,alphaCount,pyramidMultiplier,themes,dataset_id,dataset_name,category_id,category_name,subcategory_id,subcategory_name
0,anl10_cpsff_6268,Ff 6268 for cash per share,"{'id': 'analyst10', 'name': 'Performance-Weigh...","{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",GLB,1,TOP3000,MATRIX,1.0,...,14,15,1.5,[],analyst10,Performance-Weighted Analyst Estimates,analyst,Analyst,analyst-analyst-estimates,Analyst Estimates
1,anl10_cpsfq1_consensus_6279,Consensus estimate value for cash per share Q1,"{'id': 'analyst10', 'name': 'Performance-Weigh...","{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",GLB,1,TOP3000,MATRIX,1.0,...,3,3,1.5,[],analyst10,Performance-Weighted Analyst Estimates,analyst,Analyst,analyst-analyst-estimates,Analyst Estimates
2,anl10_cpsfq1_pred_surps_v0_6305,Predicted surprise version 0 for cash per shar...,"{'id': 'analyst10', 'name': 'Performance-Weigh...","{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",GLB,1,TOP3000,MATRIX,1.0,...,3,3,1.5,[],analyst10,Performance-Weighted Analyst Estimates,analyst,Analyst,analyst-analyst-estimates,Analyst Estimates
3,anl10_cpsfq1_pred_surps_v1_6289,Predicted surprise version 1 for cash per shar...,"{'id': 'analyst10', 'name': 'Performance-Weigh...","{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",GLB,1,TOP3000,MATRIX,1.0,...,0,0,1.5,[],analyst10,Performance-Weighted Analyst Estimates,analyst,Analyst,analyst-analyst-estimates,Analyst Estimates
4,anl10_cpsfq1_pred_surps_v2_6306,Predicted surprise version 2 for cash per shar...,"{'id': 'analyst10', 'name': 'Performance-Weigh...","{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",GLB,1,TOP3000,MATRIX,1.0,...,3,3,1.5,[],analyst10,Performance-Weighted Analyst Estimates,analyst,Analyst,analyst-analyst-estimates,Analyst Estimates
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13059,mws52_starttime,Start time of the event,"{'id': 'news52', 'name': 'Conference call data'}","{'id': 'news', 'name': 'News'}","{'id': 'news-news', 'name': 'News'}",GLB,1,TOP3000,MATRIX,1.0,...,16,19,1.5,"[{'id': 'AyomAkD', 'name': 'Power Pool GLB Dat...",news52,Conference call data,news,News,news-news,News
13060,mws52_talks_in_presentation,Number of talks in presentation,"{'id': 'news52', 'name': 'Conference call data'}","{'id': 'news', 'name': 'News'}","{'id': 'news-news', 'name': 'News'}",GLB,1,TOP3000,MATRIX,1.0,...,12,17,1.5,"[{'id': 'AyomAkD', 'name': 'Power Pool GLB Dat...",news52,Conference call data,news,News,news-news,News
13061,mws52_talks_in_qa,Number of talks in Q&A,"{'id': 'news52', 'name': 'Conference call data'}","{'id': 'news', 'name': 'News'}","{'id': 'news-news', 'name': 'News'}",GLB,1,TOP3000,MATRIX,1.0,...,10,21,1.5,"[{'id': 'AyomAkD', 'name': 'Power Pool GLB Dat...",news52,Conference call data,news,News,news-news,News
13062,mws52_words_in_presentation,Number of words in presentation,"{'id': 'news52', 'name': 'Conference call data'}","{'id': 'news', 'name': 'News'}","{'id': 'news-news', 'name': 'News'}",GLB,1,TOP3000,MATRIX,1.0,...,9,14,1.5,"[{'id': 'AyomAkD', 'name': 'Power Pool GLB Dat...",news52,Conference call data,news,News,news-news,News
13063,mws52_words_in_qa,Number of words in Q&A,"{'id': 'news52', 'name': 'Conference call data'}","{'id': 'news', 'name': 'News'}","{'id': 'news-news', 'name': 'News'}",GLB,1,TOP3000,MATRIX,1.0,...,31,38,1.5,"[{'id': 'AyomAkD', 'name': 'Power Pool GLB Dat...",news52,Conference call data,news,News,news-news,News

In [49]:
for cat in res_df['category_id'].unique():
    cat_df = res_df[res_df['category_id']==cat]
    print(cat, len(cat_df))

analyst 1858
fundamental 4112
institutions 11
model 5779
news 44
option 9
other 472
macro 33
sentiment 315
pv 260
risk 163
shortinterest 6
socialmedia 2

In [65]:
# cat = 'analyst'
# cat = 'earnings'
# cat = 'fundamental'
# cat = 'insiders'
# cat = 'institutions'
# cat = 'imbalance'
# cat = 'model'
# cat = 'macro'
# cat = 'news'
# cat = 'option'
# cat = 'other'
cat = 'pv'
# cat = 'risk'
# cat = 'sentiment'
# cat = 'shortinterest'
# cat = 'socialmedia'

cat_df = res_df[res_df['category_id']==cat]
cat_df

,id,description,dataset,category,subcategory,region,delay,universe,type,dateCoverage,...,userCount,alphaCount,pyramidMultiplier,themes,dataset_id,dataset_name,category_id,category_name,subcategory_id,subcategory_name
10177,adv20,Average daily volume in past 20 days,"{'id': 'pv1', 'name': 'Price Volume Data for E...","{'id': 'pv', 'name': 'Price Volume'}","{'id': 'pv-price-volume', 'name': 'Price Volume'}",GLB,1,TOP3000,MATRIX,1.0,...,573,2557,1.0,[],pv1,Price Volume Data for Equity,pv,Price Volume,pv-price-volume,Price Volume
10178,cap,Daily market capitalization (in millions),"{'id': 'pv1', 'name': 'Price Volume Data for E...","{'id': 'pv', 'name': 'Price Volume'}","{'id': 'pv-price-volume', 'name': 'Price Volume'}",GLB,1,TOP3000,MATRIX,1.0,...,823,3380,1.0,[],pv1,Price Volume Data for Equity,pv,Price Volume,pv-price-volume,Price Volume
10179,close,Daily close price,"{'id': 'pv1', 'name': 'Price Volume Data for E...","{'id': 'pv', 'name': 'Price Volume'}","{'id': 'pv-price-volume', 'name': 'Price Volume'}",GLB,1,TOP3000,MATRIX,1.0,...,1212,5583,1.0,[],pv1,Price Volume Data for Equity,pv,Price Volume,pv-price-volume,Price Volume
10180,dividend,Dividend,"{'id': 'pv1', 'name': 'Price Volume Data for E...","{'id': 'pv', 'name': 'Price Volume'}","{'id': 'pv-price-volume', 'name': 'Price Volume'}",GLB,1,TOP3000,MATRIX,1.0,...,181,620,1.0,[],pv1,Price Volume Data for Equity,pv,Price Volume,pv-price-volume,Price Volume
10181,high,Daily high price,"{'id': 'pv1', 'name': 'Price Volume Data for E...","{'id': 'pv', 'name': 'Price Volume'}","{'id': 'pv-price-volume', 'name': 'Price Volume'}",GLB,1,TOP3000,MATRIX,1.0,...,380,2312,1.0,[],pv1,Price Volume Data for Equity,pv,Price Volume,pv-price-volume,Price Volume
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10432,pv96_m21_hs_dvd_yqe,Dividend Per Share 12 Month (Gross),"{'id': 'pv96', 'name': 'Corporate Action Datas...","{'id': 'pv', 'name': 'Price Volume'}","{'id': 'pv-price-volume', 'name': 'Price Volume'}",GLB,1,TOP3000,MATRIX,1.0,...,9,9,1.0,[],pv96,Corporate Action Dataset,pv,Price Volume,pv-price-volume,Price Volume
10433,pv96_qerf_dvd,Number of times a year that the company pays a...,"{'id': 'pv96', 'name': 'Corporate Action Datas...","{'id': 'pv', 'name': 'Price Volume'}","{'id': 'pv-price-volume', 'name': 'Price Volume'}",GLB,1,TOP3000,MATRIX,1.0,...,5,5,1.0,[],pv96,Corporate Action Dataset,pv,Price Volume,pv-price-volume,Price Volume
10434,pv96_qerf_dvd_yqe,Dividend Frequency,"{'id': 'pv96', 'name': 'Corporate Action Datas...","{'id': 'pv', 'name': 'Price Volume'}","{'id': 'pv-price-volume', 'name': 'Price Volume'}",GLB,1,TOP3000,MATRIX,1.0,...,6,6,1.0,[],pv96,Corporate Action Dataset,pv,Price Volume,pv-price-volume,Price Volume
10435,pv96_td_xe_dvd,First date the security trades without entitle...,"{'id': 'pv96', 'name': 'Corporate Action Datas...","{'id': 'pv', 'name': 'Price Volume'}","{'id': 'pv-price-volume', 'name': 'Price Volume'}",GLB,1,TOP3000,MATRIX,1.0,...,9,11,1.0,[],pv96,Corporate Action Dataset,pv,Price Volume,pv-price-volume,Price Volume
10436,pv96_ycnrc_dvd,Currency code in which the latest dividend is ...,"{'id': 'pv96', 'name': 'Corporate Action Datas...","{'id': 'pv', 'name': 'Price Volume'}","{'id': 'pv-price-volume', 'name': 'Price Volume'}",GLB,1,TOP3000,MATRIX,1.0,...,14,35,1.0,[],pv96,Corporate Action Dataset,pv,Price Volume,pv-price-volume,Price Volume

In [66]:
# region = 'EUR'
# region = 'CHN'
region = 'GLB'

# universe = 'TOPCS1600'
# universe = 'TOP2000U'
universe='TOP3000'

# neutral = 'COUNTRY'
# neutral = 'MARKET'
# neutral = 'REVERSION_AND_MOMENTUM'
neutral = 'SLOW'
# neutral = 'FAST'
# neutral = 'SLOW_AND_FAST'
# neutral = 'CROWDING'
# neutral = 'STATISTICAL'

params = {
    # 'region':   'AMR', 'universe': 'TOP600',
    # 'region':   'GLB', 'universe': 'TOP3000',
    'region':   region,
    'universe': universe,
    'delay':    1,
    'neutralization': neutral
}
doc = f'{region}{universe}/{neutral}'


# delay = 'D0'
delay = 'D1'

type = 'matrix_rank'
# type = 'matrix_rank_delta5'
# type = 'matrix_rank_delta60'
# type = 'matrix_rank_backfill5'

# type = 'vector_rank'
# type = 'vector_rank_delta5'
# type = 'vector_rank_delta60'
# type = 'vector_rank_backfill5'

path_dict = {
    'matrix_rank': {
        'input_file_prefix':  f'simulate_data_results_{delay}_rank({cat})_',
        'output_file_path': f'../backfill/{doc}/[backfill_result]{cat}_matrix_{delay}_results.csv'
    },
    'matrix_rank_delta5':{
        'input_file_prefix': f'simulate_data_results_{delay}_rank(delta({cat},5))_',
        'output_file_path': f'../backfill/{doc}/[backfill_result]{cat}_matrix_{delay}_delta5_results.csv'
    },
    'matrix_rank_delta60':{
        'input_file_prefix': f'simulate_data_results_{delay}_rank(delta({cat},60))_',
        'output_file_path': f'../backfill/{doc}/[backfill_result]{cat}_matrix_{delay}_delta60_results.csv'
    },
    'matrix_rank_backfill5':{
        'input_file_prefix': f'simulate_data_results_{delay}_rank(ts_backfill({cat},5))_',
        'output_file_path': f'../backfill/{doc}/[backfill_result]{cat}_matrix_{delay}_backfill5_results.csv'
    },
    'vector_rank': {
        'input_file_prefix': f'simulate_data_results_{delay}_rank(vec_avg({cat}))_',
        'output_file_path': f'../backfill/{doc}/[backfill_result]{cat}_vector_{delay}_results.csv'
    },
    'vector_rank_delta5':{
        'input_file_prefix': f'simulate_data_results_{delay}_rank(delta(vec_avg({cat}),5))_',
        'output_file_path': f'../backfill/{doc}/[backfill_result]{cat}_vector_{delay}_delta5_results.csv'
    },
    'vector_rank_delta60': {
        'input_file_prefix': f'simulate_data_results_{delay}_rank(delta(vec_avg({cat}),60))_',
        'output_file_path': f'../backfill/{doc}/[backfill_result]{cat}_vector_{delay}_delta60_results.csv'
    },
    'vector_rank_backfill5':{
        'input_file_prefix': f'simulate_data_results_{delay}_rank(ts_backfill(vec_avg({cat}),5))_',
        'output_file_path': f'../backfill/{doc}/[backfill_result]{cat}_vector_{delay}_backfill5_results.csv'
    },
}
input_file_prefix = path_dict[type]['input_file_prefix']
output_file_path = path_dict[type]['output_file_path']
print(input_file_prefix)
print(output_file_path)

expression_list_dict = {
    'matrix_rank': [f"rank({x})" for x in cat_df.id.values],
    'matrix_rank_delta5': [f"rank(ts_delta({x},5))" for x in cat_df.id.values],
    'matrix_rank_delta60': [f"rank(ts_delta({x},60))" for x in cat_df.id.values],
    'matrix_rank_backfill5': [f"rank(ts_backfill({x},5))" for x in cat_df.id.values],
    'matrix_rank_backfill60': [f"rank(ts_backfill({x},60))" for x in cat_df.id.values],

    'vector_rank': [f"rank(vec_avg({x}))" for x in cat_df.id.values.tolist()],
    'vector_rank_delta5': [f"rank(ts_delta(vec_avg({x}),5))" for x in cat_df.id.values],
    'vector_rank_delta60': [f"rank(ts_delta(vec_avg({x}),60))" for x in cat_df.id.values],
    'vector_rank_backfill5': [f"rank(ts_backfill(vec_avg({x}),5))" for x in cat_df.id.values],
}

expression_list = expression_list_dict[type]
print(len(expression_list))

simulate_data_results_D1_rank(pv)_
../backfill/GLBTOP3000/SLOW/[backfill_result]pv_matrix_D1_results.csv
260

In [67]:
alpha_list = [
    ace.generate_alpha(
        x,
        alpha_type="REGULAR",
        region=params['region'],
        universe=params['universe'],
        delay=params['delay'],
        decay=5,
        test_period = "P2Y",
        neutralization =params['neutralization'],
        truncation = 0.05,
        pasteurization = "ON",
    ) for x in expression_list
]
alpha_list[0]

{'type': 'REGULAR',
 'settings': {'instrumentType': 'EQUITY',
  'region': 'GLB',
  'universe': 'TOP3000',
  'delay': 1,
  'decay': 5,
  'neutralization': 'SLOW',
  'truncation': 0.05,
  'pasteurization': 'ON',
  'testPeriod': 'P2Y',
  'unitHandling': 'VERIFY',
  'nanHandling': 'OFF',
  'maxTrade': 'OFF',
  'language': 'FASTEXPR',
  'visualization': False},
 'regular': 'rank(adv20)'}

In [72]:
import os
import time

k = 30
print(f"alpha_count={len(alpha_list)}, delay={delay}, doc={doc}, cat={cat}")
print(f"input_file_prefix={input_file_prefix}\noutput_file_path={output_file_path}")

for i in range(0, len(alpha_list), k):
    # if i<=2880: continue
    print(i, i+k, len(alpha_list))
    output_file = f'../backfill/{doc}/{input_file_prefix}{i}_{i+k}.csv'
    if os.path.exists(output_file):
        continue
    else:
        tmp_alpha_list = alpha_list[i:i+k]
        result = ace.simulate_alpha_list_multi(
            s,
            tmp_alpha_list,
            limit_of_concurrent_simulations=3,
            limit_of_multi_simulations=5,
        )
        not_empty_result = [r for r in result if r['alpha_id'] is not None]
        if len(not_empty_result)>0:
            output_df = hf.prettify_result(not_empty_result, clickable_alpha_id=False)
            output_df.to_csv(output_file, index=False)
    time.sleep(2)
print('Done')

alpha_count=260, delay=D1, doc=GLBTOP3000/SLOW, cat=pv
input_file_prefix=simulate_data_results_D1_rank(pv)_
output_file_path=../backfill/GLBTOP3000/SLOW/[backfill_result]pv_matrix_D1_results.csv
0 30 260
30 60 260
60 90 260
90 120 260

100%|██████████| 6/6 [29:46<00:00, 297.68s/it]

120 150 260

100%|██████████| 6/6 [28:17<00:00, 282.92s/it]

150 180 260

100%|██████████| 6/6 [29:48<00:00, 298.12s/it]

180 210 260

100%|██████████| 6/6 [28:05<00:00, 280.96s/it]

210 240 260

100%|██████████| 6/6 [28:48<00:00, 288.01s/it]

240 270 260

  0%|          | 0/4 [01:21<?, ?it/s]
2026-03-03 21:52:10,222 - ace - INFO - Trying re-login, wait 100 seconds

ConnectionError: HTTPSConnectionPool(host='api.worldquantbrain.com', port=443): Max retries exceeded with url: /simulations/45YnurdZa4RAa8isyBieJIb (Caused by NewConnectionError("HTTPSConnection(host='api.worldquantbrain.com', port=443): Failed to establish a new connection: [Errno 51] Network is unreachable"))

In [69]:
import os
import pandas as pd

print(output_file_path)

result_df = pd.DataFrame()
for f in os.listdir(f'../backfill/{doc}'):
    if f.startswith(input_file_prefix):
        # print(f)
        result_df = pd.concat([
            result_df,
            pd.read_csv( f'../backfill/{doc}/{f}')
        ], ignore_index=True)

print(result_df.shape)
result_df.sort_values('sharpe').to_csv(output_file_path, index=False)

../backfill/GLBTOP3000/SLOW/[backfill_result]pv_matrix_D1_results.csv
(53, 28)

# Rename

In [39]:
# 文件名重命名
for f in os.listdir(f'../backfill/{doc}'):
    if f.startswith('simulate_data_results_rankanalyst)_'):
        new_f = f[:22] + 'D1_rank(' + f[26:]
        old_path = f'../backfill/{doc}/{f}'
        new_path = f'../backfill/{doc}/{new_f}'
        print(old_path)
        print(new_path)
        # os.rename(old_path, new_path)

# Combine Alphas

In [265]:
import pandas as pd
factor_files = [
    # '../backfill/IND/[matrix]field_df_IND_TOP500_delay1.csv',
    # '../backfill/IND/[vector]field_df_IND_TOP500_delay1.csv',
    '../backfill/AMR/[field_df]AMR_TOP600_matrix_delay1.csv',
    '../backfill/AMR/[field_df]AMR_TOP600_vector_delay1.csv'
]
factor_df = pd.concat([ pd.read_csv(f) for f in factor_files ])
print(factor_df.shape)
factor_df.head()

(16986, 22)

,Unnamed: 0,id,description,dataset,category,subcategory,region,delay,universe,type,...,userCount,alphaCount,pyramidMultiplier,themes,dataset_id,dataset_name,category_id,category_name,subcategory_id,subcategory_name
0,0,anl10_bpsff_5551,Ff 5551 for book value per share,"{'id': 'analyst10', 'name': 'Performance-Weigh...","{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",AMR,1,TOP600,MATRIX,...,1,1,1.7,[],analyst10,Performance-Weighted Analyst Estimates,analyst,Analyst,analyst-analyst-estimates,Analyst Estimates
1,1,anl10_bpsfq1_consensus_5550,Consensus estimate value for book value per sh...,"{'id': 'analyst10', 'name': 'Performance-Weigh...","{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",AMR,1,TOP600,MATRIX,...,0,0,1.7,[],analyst10,Performance-Weighted Analyst Estimates,analyst,Analyst,analyst-analyst-estimates,Analyst Estimates
2,2,anl10_bpsfq1_pred_surps_v0_5545,Predicted surprise version 0 for book value pe...,"{'id': 'analyst10', 'name': 'Performance-Weigh...","{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",AMR,1,TOP600,MATRIX,...,1,2,1.7,[],analyst10,Performance-Weighted Analyst Estimates,analyst,Analyst,analyst-analyst-estimates,Analyst Estimates
3,3,anl10_bpsfq1_pred_surps_v1_5557,Predicted surprise version 1 for book value pe...,"{'id': 'analyst10', 'name': 'Performance-Weigh...","{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",AMR,1,TOP600,MATRIX,...,0,0,1.7,[],analyst10,Performance-Weighted Analyst Estimates,analyst,Analyst,analyst-analyst-estimates,Analyst Estimates
4,4,anl10_bpsfq1_pred_surps_v2_5564,Predicted surprise version 2 for book value pe...,"{'id': 'analyst10', 'name': 'Performance-Weigh...","{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",AMR,1,TOP600,MATRIX,...,0,0,1.7,[],analyst10,Performance-Weighted Analyst Estimates,analyst,Analyst,analyst-analyst-estimates,Analyst Estimates

In [266]:
def extract_last_parentheses(text):
    """
    提取字符串中最后一个括号内的内容
    参数:
        text: 包含括号的字符串
    返回:
        最后一个括号内的内容，如果找不到括号返回None
    """
    # 查找最后一个 '(' 和最后一个 ')'
    left_idx = text.rfind('(')
    right_idx = text.find(')')
    # 确保找到两个括号且左括号在右括号之前
    if left_idx != -1 and right_idx != -1 and left_idx < right_idx:
        alpha = text[left_idx+1: right_idx].strip()
        alpha = alpha.split(',')[0].strip()
        alpha = alpha.strip('-')
        return alpha
    return None

file_ret_dict = {
    'rank': [
                '../backfill/AMR/analyst_matrix_D1_results.csv',

                '../backfill/AMR/shortinterest_vector_D1_results.csv',
                '../backfill/AMR/analyst_vector_D1_results.csv',
                '../backfill/AMR/earnings_vector_D1_results.csv',
                '../backfill/AMR/fundamental_vector_D1_results.csv',
                '../backfill/AMR/insiders_vector_D1_results.csv',
                '../backfill/AMR/institutions_vector_D1_results.csv',
                '../backfill/AMR/macro_vector_D1_results.csv',
                '../backfill/AMR/model_vector_D1_results.csv',
                '../backfill/AMR/news_vector_D1_results.csv',
                '../backfill/AMR/option_vector_D1_results.csv',
                '../backfill/AMR/other_vector_D1_results.csv',
                '../backfill/AMR/pv_vector_D1_results.csv',
                '../backfill/AMR/risk_vector_D1_results.csv',
                '../backfill/AMR/sentiment_vector_D1_results.csv',
             ],
    'delta5_rank': [],
    'delta60_rank': [],
    'backfill60_rank': [],
    'negetive_candidate': []
}

In [268]:
final_values_df = pd.DataFrame()

for type in file_ret_dict:
    files = file_ret_dict[type]
    if len(files)>0:
        values_df = pd.concat([
            pd.read_csv(f).drop_duplicates().assign(file_name=f) for f in files
        ])
        print(type, values_df.shape)
        values_df['alpha'] = values_df['expression'].apply(extract_last_parentheses)
        final_values_df = pd.concat([final_values_df, values_df])

final_values_df = pd.merge(final_values_df,factor_df[['id','category_id']], how='left', left_on='alpha', right_on='id')
print('final_values_df', final_values_df.shape)

# Save final_values_df to CSV file
# final_values_df.to_csv('../backfill/IND/[backfill_result]D1_results.csv')

rank (5057, 24)
final_values_df (5057, 27)

In [64]:
final_values_df[(final_values_df['long_count']>=100)]

Empty DataFrame
Columns: [pnl, book_size, long_count, short_count, turnover, returns, drawdown, margin, sharpe, fitness, start_date, investability_constrained, alpha_id, expression, concentrated_weight, high_turnover, low_2y_sharpe, low_fitness, low_robust_universe_sharpe, low_sharpe, low_sub_universe_sharpe, low_turnover, matches_pyramid, matches_themes, file_name, alpha, id, category_id]
Index: []

[0 rows x 28 columns]

In [269]:
final_values_df.columns

Index(['pnl', 'book_size', 'long_count', 'short_count', 'turnover', 'returns',
       'drawdown', 'margin', 'sharpe', 'fitness', 'start_date',
       'investability_constrained', 'alpha_id', 'expression',
       'concentrated_weight', 'high_turnover', 'low_2y_sharpe', 'low_fitness',
       'low_sharpe', 'low_sub_universe_sharpe', 'low_turnover',
       'matches_pyramid', 'matches_themes', 'file_name', 'alpha', 'id',
       'category_id'],
      dtype='object')

In [66]:
final_values_df[
                (final_values_df['long_count']>=100)&
                (final_values_df['low_2y_sharpe']=='PASS')&
                (final_values_df['low_robust_universe_sharpe']=='PASS')&
                (final_values_df['low_fitness']=='PASS')&
                (final_values_df['low_sub_universe_sharpe']=='PASS')&
                (final_values_df['sharpe']>1)
][['file_name','alpha_id','category_id','expression']]

,file_name,alpha_id,category_id,expression
1735,../backfill/IND/other_matrix_results.csv,1Y5vnP7M,other,rank(oth335_combined_all_region_hedge)
1736,../backfill/IND/other_matrix_results.csv,N1oM53be,other,rank(oth335_combined_all_region_mind)
4004,../backfill/IND/analyst_vector_results.csv,88qEZ3xX,analyst,rank(vec_avg(anl44_best_eps_4wk_chg))
4005,../backfill/IND/analyst_vector_results.csv,j2QxQ3VO,analyst,rank(vec_avg(eps_estimate_4wk_change))
5679,../backfill/IND/model_matrix_results.csv,P0eNzNZL,model,rank(forecasted_surprise_year2_revenue)
...,...,...,...,...
9085,../backfill/IND/negative_candidates_results.csv,RRXo13k1,model,rank(-mdl26_score)
9086,../backfill/IND/negative_candidates_results.csv,Jjlkx6Z2,risk,rank(-ts_delta(residualized_return_india_equit...
9087,../backfill/IND/negative_candidates_results.csv,wp6AEmJx,model,rank(-star_arm_score_5)
9088,../backfill/IND/negative_candidates_results.csv,e7AP0G9d,risk,rank(-residualized_return_india_top500_equity)
9089,../backfill/IND/negative_candidates_results.csv,gJv5QnEe,risk,rank(-ts_delta(residualized_return_india_top50...

# generate_merge_df

In [26]:
for category in final_values_df['category_id'].unique():
    # if category in ('pv'):
    if category in ('other'):
        cat_final_values_df = final_values_df[final_values_df['category_id'] == category]
        q_cat_final_values_df = cat_final_values_df[
                                        (cat_final_values_df['long_count']>=100) &
                                        (cat_final_values_df['sharpe']>1.2)
                                    ]
        print(category, q_cat_final_values_df.shape)

        import itertools
        expressions = q_cat_final_values_df['expression'].tolist()
        combinations = list(itertools.combinations(expressions, 2))
        print(f"总共生成 {len(combinations)} 个组合")

        # 迭代所有组合
        combine_expressions1 = [f'a={expr1};b={expr2};a+b'                                for i, (expr1, expr2) in enumerate(combinations)]
        combine_expressions2_1 = [f'a={expr1};b={expr2};ts_regression(a,b,20,rettype=1)'  for i, (expr1, expr2) in enumerate(combinations)]
        combine_expressions2_2 = [f'a={expr2};b={expr1};ts_regression(a,b,20,rettype=1)'  for i, (expr1, expr2) in enumerate(combinations)]
        combine_expressions3_1 = [f'a={expr1};b={expr2};ts_regression(a,b,20,rettype=2)'  for i, (expr1, expr2) in enumerate(combinations)]
        combine_expressions3_2 = [f'a={expr2};b={expr1};ts_regression(a,b,20,rettype=2)'  for i, (expr1, expr2) in enumerate(combinations)]
        combine_expressions4_1 = [f'trade_when({expr1}>0.5,{expr2},{expr1}<=0.5)'         for i, (expr1, expr2) in enumerate(combinations)]
        combine_expressions4_2 = [f'trade_when({expr2}>0.5,{expr1},{expr2}<=0.5)'         for i, (expr1, expr2) in enumerate(combinations)]
        combine_expressions = combine_expressions1 + combine_expressions2_1 + combine_expressions3_1 + combine_expressions4_1 + combine_expressions2_2 + combine_expressions3_2 + combine_expressions4_2
        alpha_list = [
            ace.generate_alpha(
                x,
                alpha_type="REGULAR",
                region="IND",
                universe="TOP500",
                delay=1,
                decay=5,
                test_period = "P2Y",
                neutralization = "INDUSTRY",
                truncation = 0.05,
                pasteurization = "ON",
            ) for x in combine_expressions
        ]
print(len(alpha_list))

other (23, 28)
总共生成 253 个组合
759

In [26]:
import os
import time

k = 30
for i in range(0, len(alpha_list), k):
    print(i, i+k)
    output_file = f'../backfill/IND/[simulate_data_results]other_combine_factors_{i}_{i+k}.csv'
    if os.path.exists(output_file):
        continue
    else:
        tmp_alpha_list = alpha_list[i:i+k]
        result = ace.simulate_alpha_list_multi(
            s,
            tmp_alpha_list,
            limit_of_concurrent_simulations=3,
            limit_of_multi_simulations=5,
        )
        not_empty_result = [r for r in result if r['alpha_id'] is not None]
        if len(not_empty_result)>0:
            output_df = hf.prettify_result(not_empty_result, clickable_alpha_id=False)
            output_df.to_csv(output_file, index=False)
    time.sleep(2)
print('Done')

0 30
30 60

  0%|          | 0/6 [00:05<?, ?it/s]

KeyboardInterrupt:

In [24]:
import os
import pandas as pd

result_df = pd.DataFrame()
for f in os.listdir(f'../backfill/IND'):
    if f.startswith(f'[simulate_data_results]pv_combine_factors_'):
        # print(f)
        result_df = pd.concat([
            result_df,
            pd.read_csv( f'../backfill/IND/{f}')
        ], ignore_index=True)

print(result_df.shape)
# result_df.sort_values('sharpe').to_csv(f'../backfill/{doc}/{cat}_vector_{delay}_results.csv', index=False)
result_df.sort_values('sharpe').to_csv(f'../backfill/IND/[simulate_data_results]other_combine_factors_results.csv', index=False)

(315, 24)

# generate_negative_df

In [33]:
expression_list = ['(-'.join(expr.split('(',1)) for expr in final_values_df[
                # (final_values_df['low_2y_sharpe']=='PASS')&
                # (final_values_df['low_robust_universe_sharpe']=='PASS')&
                # (final_values_df['low_fitness']=='PASS')&
                # (final_values_df['low_sub_universe_sharpe']=='PASS')&
                (# (final_values_df['sharpe']>1)|
                 (final_values_df['sharpe']<-1.5)
                )
]['expression']]

alpha_list = [
    ace.generate_alpha(
        x,
        alpha_type="REGULAR",
        region="IND",
        universe="TOP500",
        delay=1,
        decay=5,
        test_period = "P2Y",
        neutralization = "INDUSTRY",
        truncation = 0.05,
        pasteurization = "ON",
    ) for x in expression_list
]

alpha_list[0]

{'type': 'REGULAR',
 'settings': {'instrumentType': 'EQUITY',
  'region': 'IND',
  'universe': 'TOP500',
  'delay': 1,
  'decay': 5,
  'neutralization': 'INDUSTRY',
  'truncation': 0.05,
  'pasteurization': 'ON',
  'testPeriod': 'P2Y',
  'unitHandling': 'VERIFY',
  'nanHandling': 'OFF',
  'maxTrade': 'OFF',
  'language': 'FASTEXPR',
  'visualization': False},
 'regular': 'rank(-fnd17_pr5dayprc)'}

In [34]:
expression_list

['rank(-fnd17_pr5dayprc)',
 'rank(-fnd17_chpctpricewtd)',
 'rank(-fnd17_pr1dayprc)',
 'rank(-idiosyncratic_return_fraction)',
 'rank(-pv47_spret)',
 'rank(-pv47_for_statssimple_only_spret)',
 'rank(-vec_avg(region_exposure_percent_minimum))',
 'rank(-vec_avg(max_trade_price))',
 'rank(-vec_avg(insd5_nm_kor))',
 'rank(-headline_mention_count_2)',
 'rank(-oth532_global_daily_specificreturn)',
 'rank(-oth532_emerging_daily_specificreturn)',
 'rank(-oth532_asia_ase2_daily_specificreturn)',
 'rank(-vec_avg(oth696_lawsuit_positive))',
 'rank(-vec_avg(rd_negative_event_count))',
 'rank(-vec_avg(oth696_investments_negative))',
 'rank(-vec_avg(oth696_productdesignlifecyclemanagement_positive))',
 'rank(-vec_avg(oth696_managementlegalregulatoryframework_negative))',
 'rank(-vec_avg(oth696_geostability_positive))',
 'rank(-vec_avg(oth696_customerwelfare_positive))',
 'rank(-vec_avg(leg1_spread_value))',
 'rank(-vec_avg(oth696_stockprice_negative))',
 'rank(-vec_avg(leg2_aggregate_notional_quantity))',
 'rank(-vec_avg(oth532_spret))',
 'rank(-vec_avg(oth696_airquality_positive))',
 'rank(-snt21_4neg_max)',
 'rank(-snt21_5pos_max)',
 'rank(-snt21_5pos_conf_up)',
 'rank(-snt21_4neg_mean)',
 'rank(-snt21_5pos_conf_low)',
 'rank(-snt21_4neg_median)',
 'rank(-snt21_4neg_conf_up)',
 'rank(-snt21_5pos_mean)',
 'rank(-vec_avg(other_executive_numeric_word_ratio_presentation))',
 'rank(-vec_avg(reference_index_currency_3))',
 'rank(-vec_avg(anl4_detailrecv4_est))',
 'rank(-vec_avg(anl83_ceo_neg_logit_qa))',
 'rank(-vec_avg(eps_estimate_4wk_down_count))',
 'rank(-vec_avg(anl44_best_eps_4wk_dn))',
 'rank(-vec_avg(pretaxprofit_estimates_down_4w))',
 'rank(-residualized_return_india_top500_equity)',
 'rank(-residualized_return_india_equity_universe)',
 'rank(-residualized_return_india_top200_equity)',
 'rank(-rsk68_residual_return)',
 'rank(-residualized_return_india_single_stock_futures)',
 'rank(-star_arm_score_5)',
 'rank(-mdl26_score)',
 'rank(-score_avg_5d)',
 'rank(-mdl26_sma_arm_score_5)',
 'rank(-composite_score_qsg_india)',
 'rank(-three_month_revision_fy1_earnings_india)',
 'rank(-mdl177_indrelrtn5d_)',
 'rank(-three_month_revision_fy2_earnings_india)',
 'rank(-mdl177_fc_epsrm)',
 'rank(-mdl26_rcmmndtn_mn_chng_90)',
 'rank(-avg_change_analyst_recommendation_90d)',
 'rank(-mdl177_chgepsp)',
 'rank(-mdl177_fc_numrevy1)',
 'rank(-star_arm_rec_mean_prior7)',
 'rank(-avg_change_analyst_recommendation_7d)',
 'rank(-mdl26_rcmmndtn_mn_chng_7)',
 'rank(-mdl177_chgnpm)',
 'rank(-mdl177_pctchgeps)',
 'rank(-mdl177_fc_rev3y1)',
 'rank(-mdl26_num_downgrades_7)',
 'rank(-count_analyst_recommendation_downgrades_7d)',
 'rank(-avg_change_analyst_recommendation_30d)',
 'rank(-mdl26_sm_rcmmndtn_mn_chng_30)',
 'rank(-vec_avg(mdl135_d3_if))',
 'rank(-vec_avg(mdl135_d3_ivn))',
 'rank(-vec_avg(mdl135_d3_iv))',
 'rank(-vec_avg(mdl135_d5_if))',
 'rank(-vec_avg(mdl135_d5_icc))',
 'rank(-vec_avg(mdl135_d5_bb))',
 'rank(-vec_avg(mdl135_d5_iv))',
 'rank(-vec_avg(mdl135_d3_icc))',
 'rank(-vec_avg(mdl135_d3_fmc))',
 'rank(-vec_avg(mdl135_d3_lda))',
 'rank(-vec_avg(mdl135_d3_bb))',
 'rank(-vec_avg(mdl135_d3_vbo))',
 'rank(-vec_avg(mdl135_d3_tpv))',
 'rank(-vec_avg(mdl135_d3_isr))',
 'rank(-vec_avg(mdl135_d01_bb))',
 'rank(-vec_avg(mdl135_d3_vme))',
 'rank(-vec_avg(mdl135_d5_oa))',
 'rank(-vec_avg(mdl135_vlc))',
 'rank(-vec_avg(mdl135_d01_icc))',
 'rank(-vec_avg(mdl135_d7_oc))',
 'rank(-vec_avg(mdl135_d3_ifm))',
 'rank(-vec_avg(mdl135_d5_fmc))',
 'rank(-vec_avg(mdl135_d3ntr))',
 'rank(-vec_avg(mdl135_d5_vbo))',
 'rank(-vec_avg(mdl135_d5_isr))',
 'rank(-vec_avg(mdl135_d5ntr))',
 'rank(-vec_avg(mdl135_macd_3d))',
 'rank(-vec_avg(mdl135_d5_lda))',
 'rank(-vec_avg(mdl135_d6_oc))',
 'rank(-vec_avg(mdl135_macd_2d))',
 'rank(-vec_avg(mdl135_d8_oc))',
 'rank(-vec_avg(mdl135_d5_vme))',
 'rank(-vec_avg(mdl135_willimsr_5d))',
 'rank(-vec_avg(mdl135_d3_oa))',
 'rank(-vec_avg(mdl135_d5_ivn))',
 'rank(-vec_avg(mdl135_macd_4d))',
 'rank(-vec_avg(mdl135_d01_if))',
 'rank(-vec_avg(mdl135_macd_1d))',
 'rank(-vec_avg(triple_ema_rate_change_3d))',
 'rank(-vec_avg(mdl135_willimsr_10d))',
 'rank(-vec_avg(mdl135_d5_oc))',
 'rank(-vec_avg(mdl135_willimsr_3d))',
 'rank(-vec_avg(mdl135_d04_isrs))',
 'rank(-vec_avg(mdl135_d02_isrs))',
 'rank(-vec_avg(mdl135_d01_iv))',
 'rank(-vec_avg(mdl135_d01_isrs))',
 'rank(-vec_avg(mdl135_d01_oa))',
 'rank(-vec_avg(mdl135_d3_oc))',
 'rank(-vec_avg(mdl135_ou))',
 'rank(-vec_avg(mdl135_d5_ifm))',
 'rank(-vec_avg(mdl135_d2_ou))',
 'rank(-vec_avg(mdl135_d02_bb))',
 'rank(-vec_avg(mdl135_d01_vme))',
 'rank(-vec_avg(mdl135_ist))',
 'rank(-vec_avg(mdl135_d2_oc))',
 'rank(-vec_avg(mdl135_d4_oc))',
 'rank(-vec_avg(mdl135_d3_os))',
 'rank(-vec_avg(mdl135_d01_isr))',
 'rank(-vec_avg(mdl135_d02_icc))',
 'rank(-ts_delta(idiosyncratic_return_fraction, 5))',
 'rank(-ts_delta(pv47_spret, 5))',
 'rank(-ts_delta(pv47_for_statssimple_only_spret, 5))',
 'rank(-ts_delta(session_1430to1430_total_traded_volume, 5))',
 'rank(-ts_delta(session_1430to1430_initial_trade_price, 5))',
 'rank(-ts_delta(session_1430to1430_min_trade_price, 5))',
 'rank(-ts_delta(session_1430to1430_volume_weighted_avg_price, 5))',
 'rank(-ts_delta(session_1430to1430_final_trade_price, 5))',
 'rank(-ts_delta(session_1430to1430_max_trade_price, 5))',
 'rank(-ts_delta(session_1430to1430_market_value, 5))',
 'rank(-ts_delta(mws52_sentences_in_qa,5))',
 'rank(-ts_delta(mws52_conference_call_participants,5))',
 'rank(-ts_delta(mws52_pparagraphs_in_qa,5))',
 'rank(-ts_delta(mws52_chars_in_qa,5))',
 'rank(-ts_delta(event_frequency_label,5))',
 'rank(-ts_delta(mws52_questions_in_qa,5))',
 'rank(-ts_delta(mws52_talks_in_qa,5))',
 'rank(-ts_delta(mws52_words_in_qa,5))',
 'rank(-ts_delta(mws52_questions_in_presentation,5))',
 'rank(- ts_delta( fnd17_chpctpricewtd, 60) )',
 'rank(- ts_delta( fnd17_pr1dayprc, 60) )',
 'rank(- ts_delta( fnd4_chinascope_secmap, 60) )',
 'rank(- ts_delta( fnd17_ttmdebteps, 60) )',
 'rank(- ts_delta( fnd17_pr5dayprc, 60) )',
 'rank(-ts_delta(vec_avg(operator_forward_looking_sentiment_presentation),60))',
 'rank(-ts_delta(vec_avg(relative_index_return_percent_limited),60))',
 'rank(-ts_delta(vec_avg(success_likelihood_score_4),60))',
 'rank(-ts_delta(vec_avg(mean_daily_relative_performance),60))',
 'rank(-ts_delta(vec_avg(analyst_positive_sentiment_logit_presentation),60))',
 'rank(-ts_delta(vec_avg(analyst_negative_sentiment_logit_presentation),60))',
 'rank(-ts_delta(vec_avg(relative_percent_return_today_limited),60))',
 'rank(-ts_delta(vec_avg(anl45_limited_tot_ret),60))',
 'rank(-ts_delta(vec_avg(anl45_limited_treynor_ratio),60))',
 'rank(-ts_delta(vec_avg(anl45_limited_tot_ret_wo_fx),60))',
 'rank(-ts_delta(vec_avg(anl45_limited_stock_ret_per),60))',
 'rank(-ts_delta(vec_avg(benchmark_index_return_percent_limited),60))',
 'rank(-ts_delta(vec_avg(anl45_limited_bias_weighted_ret),60))',
 'rank(-ts_delta(vec_avg(anl83_serp_erf),60))',
 'rank(-ts_delta(vec_avg(anl83_ceo_pos_logit_qa),60))',
 'rank(-ts_delta(residualized_return_india_top500_equity,60))',
 'rank(-ts_delta(residualized_return_india_equity_universe,60))',
 'rank(-ts_delta(rsk68_residual_return,60))',
 'rank(-ts_delta(residualized_return_india_top200_equity,60))',
 'rank(-ts_delta(residualized_return_india_single_stock_futures,60))',
 'rank(-ts_backfill(oth532_asia_ase2_daily_specificreturn,60))',
 'rank(-ts_backfill(oth532_global_daily_specificreturn,60))',
 'rank(-ts_backfill(oth532_emerging_daily_specificreturn,60))']

In [36]:
import os
import time

k = 30
for i in range(0, len(alpha_list), k):
    print(i, i+k)
    output_file = f'../backfill/IND/simulate_data_results_negative_candidates_{i}_{i+k}.csv'
    if os.path.exists(output_file):
        continue
    else:
        tmp_alpha_list = alpha_list[i:i+k]
        result = ace.simulate_alpha_list_multi(
            s,
            tmp_alpha_list,
            limit_of_concurrent_simulations=3,
            limit_of_multi_simulations=5,
        )
        not_empty_result = [r for r in result if r['alpha_id'] is not None]
        if len(not_empty_result)>0:
            output_df = hf.prettify_result(not_empty_result, clickable_alpha_id=False)
            output_df.to_csv(output_file, index=False)
    time.sleep(2)

print('Done')

0 30
30 60

100%|██████████| 6/6 [07:21<00:00, 73.51s/it]

60 90

100%|██████████| 6/6 [07:45<00:00, 77.56s/it]

90 120

100%|██████████| 6/6 [11:12<00:00, 112.10s/it]

120 150

100%|██████████| 6/6 [10:14<00:00, 102.34s/it]

150 180

100%|██████████| 5/5 [05:59<00:00, 71.89s/it]

Done

In [37]:
import os
import pandas as pd

result_df = pd.DataFrame()
for f in os.listdir(f'../backfill/IND'):
    if f.startswith(f'simulate_data_results_negative_candidates_'):
    # if f.startswith(f'simulate_data_results_{delay}_rank({cat})_'):
        # print(f)
        result_df = pd.concat([
            result_df,
            pd.read_csv( f'../backfill/IND/{f}' )
        ], ignore_index=True)
print(result_df.shape)

result_df.sort_values('sharpe').to_csv(f'../backfill/IND/negative_candidates_results.csv', index=False)

(174, 23)